/**
 * Multi-city dataset and configuration for Ghost Bus Tracker
 * Supports Twin Cities (Metro Transit), San Francisco (SFMTA Muni),
 * Chicago (CTA), Boston (MBTA), and New York City (MTA).
 */

import { DEFAULT_LATEST, DEFAULT_HISTORY } from "./snapshot_data.js";

export const CITY_PRESETS = [
  {
    id: "twin-cities",
    name: "Twin Cities (Metro Transit)",
    shortName: "Twin Cities",
    agency: "Metro Transit",
    city: "Minneapolis–Saint Paul, MN",
    icon: "🏙️",
    website: "https://www.metrotransit.org",
  },
  {
    id: "sf",
    name: "San Francisco (SFMTA Muni)",
    shortName: "San Francisco",
    agency: "SFMTA (Muni)",
    city: "San Francisco, CA",
    icon: "🌉",
    website: "https://www.sfmta.com",
  },
  {
    id: "chicago",
    name: "Chicago (CTA)",
    shortName: "Chicago",
    agency: "Chicago Transit Authority",
    city: "Chicago, IL",
    icon: "🌆",
    website: "https://www.transitchicago.com",
  },
  {
    id: "boston",
    name: "Boston (MBTA)",
    shortName: "Boston",
    agency: "MBTA",
    city: "Boston, MA",
    icon: "🏛️",
    website: "https://www.mbta.com",
  },
  {
    id: "nyc",
    name: "New York (MTA)",
    shortName: "New York",
    agency: "MTA New York City Transit",
    city: "New York, NY",
    icon: "🗽",
    website: "https://new.mta.info",
  },
];

export const CITY_ALIASES = {
  "twin-cities": "twin-cities",
  "twincities": "twin-cities",
  "mpls": "twin-cities",
  "minneapolis": "twin-cities",
  "stpaul": "twin-cities",
  "st-paul": "twin-cities",
  "msp": "twin-cities",
  "metro-transit": "twin-cities",
  "sf": "sf",
  "sfmta": "sf",
  "muni": "sf",
  "san-francisco": "sf",
  "sanfrancisco": "sf",
  "chicago": "chicago",
  "cta": "chicago",
  "chi": "chicago",
  "boston": "boston",
  "mbta": "boston",
  "nyc": "nyc",
  "mta": "nyc",
  "new-york": "nyc",
  "new-york-city": "nyc",
  "nyct": "nyc",
};

export const SF_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "SFMTA (San Francisco Muni)",
  city: "San Francisco, CA",
  transit_system: "SFMTA (Muni)",
  region: "San Francisco Bay Area, California",
  state: "California",
  country: "USA",
  total_scheduled_trips: 542,
  total_tracked_vehicles: 452,
  total_ghost_trips: 90,
  ghost_bus_rate_pct: 16.61,
  vehicle_tracking_rate_pct: 83.39,
  overall_on_time_pct: 69.47,
  delay_distribution: {
    early: 28,
    on_time: 314,
    minor_delay: 84,
    severe_delay: 26,
    ghost: 90,
    canceled: 6,
  },
  mean_delay_sec: 152.4,
  median_delay_sec: 65.0,
  worst_routes_by_ghost: [
    {
      route_id: "14R",
      route_name: "14R Mission Rapid",
      total_trips: 28,
      tracked_vehicles: 16,
      ghost_trips: 12,
      canceled_trips: 2,
      on_time_trips: 10,
      delayed_trips: 6,
      ghost_rate_pct: 42.86,
      on_time_pct: 62.5,
      avg_delay_sec: 288.0,
      max_delay_sec: 720,
    },
    {
      route_id: "38R",
      route_name: "38R Geary Rapid",
      total_trips: 32,
      tracked_vehicles: 20,
      ghost_trips: 12,
      canceled_trips: 1,
      on_time_trips: 14,
      delayed_trips: 6,
      ghost_rate_pct: 37.5,
      on_time_pct: 70.0,
      avg_delay_sec: 204.0,
      max_delay_sec: 610,
    },
    {
      route_id: "1",
      route_name: "1 California",
      total_trips: 18,
      tracked_vehicles: 12,
      ghost_trips: 6,
      canceled_trips: 0,
      on_time_trips: 8,
      delayed_trips: 4,
      ghost_rate_pct: 33.33,
      on_time_pct: 66.67,
      avg_delay_sec: 312.0,
      max_delay_sec: 680,
    },
    {
      route_id: "22",
      route_name: "22 Fillmore",
      total_trips: 22,
      tracked_vehicles: 15,
      ghost_trips: 7,
      canceled_trips: 1,
      on_time_trips: 9,
      delayed_trips: 6,
      ghost_rate_pct: 31.82,
      on_time_pct: 60.0,
      avg_delay_sec: 348.0,
      max_delay_sec: 780,
    },
    {
      route_id: "8",
      route_name: "8 Bayshore",
      total_trips: 20,
      tracked_vehicles: 14,
      ghost_trips: 6,
      canceled_trips: 0,
      on_time_trips: 8,
      delayed_trips: 6,
      ghost_rate_pct: 30.0,
      on_time_pct: 57.14,
      avg_delay_sec: 420.0,
      max_delay_sec: 910,
    },
    {
      route_id: "49",
      route_name: "49 Van Ness / Mission",
      total_trips: 24,
      tracked_vehicles: 17,
      ghost_trips: 7,
      canceled_trips: 0,
      on_time_trips: 13,
      delayed_trips: 4,
      ghost_rate_pct: 29.17,
      on_time_pct: 76.47,
      avg_delay_sec: 138.0,
      max_delay_sec: 420,
    },
    {
      route_id: "30",
      route_name: "30 Stockton",
      total_trips: 22,
      tracked_vehicles: 16,
      ghost_trips: 6,
      canceled_trips: 1,
      on_time_trips: 10,
      delayed_trips: 6,
      ghost_rate_pct: 27.27,
      on_time_pct: 62.5,
      avg_delay_sec: 330.0,
      max_delay_sec: 660,
    },
    {
      route_id: "N",
      route_name: "N Judah Metro",
      total_trips: 26,
      tracked_vehicles: 20,
      ghost_trips: 6,
      canceled_trips: 0,
      on_time_trips: 14,
      delayed_trips: 6,
      ghost_rate_pct: 23.08,
      on_time_pct: 70.0,
      avg_delay_sec: 210.0,
      max_delay_sec: 540,
    },
    {
      route_id: "T",
      route_name: "T Third Street Metro",
      total_trips: 18,
      tracked_vehicles: 14,
      ghost_trips: 4,
      canceled_trips: 0,
      on_time_trips: 9,
      delayed_trips: 5,
      ghost_rate_pct: 22.22,
      on_time_pct: 64.29,
      avg_delay_sec: 258.0,
      max_delay_sec: 590,
    },
    {
      route_id: "5R",
      route_name: "5R Fulton Rapid",
      total_trips: 16,
      tracked_vehicles: 13,
      ghost_trips: 3,
      canceled_trips: 0,
      on_time_trips: 10,
      delayed_trips: 3,
      ghost_rate_pct: 18.75,
      on_time_pct: 76.92,
      avg_delay_sec: 168.0,
      max_delay_sec: 390,
    },
  ],
  sample_ghost_trips: [
    {
      trip_id: "SF-940212",
      route_id: "14R",
      start_time: "08:14",
      status: "SCHEDULED",
      reason: "No vehicle assigned and no GPS transponder broadcast on Mission St corridor",
    },
    {
      trip_id: "SF-881230",
      route_id: "38R",
      start_time: "08:19",
      status: "SCHEDULED",
      reason: "Assigned coach #6521 dropped transponder signal past Park Presidio",
    },
    {
      trip_id: "SF-912044",
      route_id: "1",
      start_time: "08:22",
      status: "SCHEDULED",
      reason: "Unfilled operator run; vehicle never departed California & Drumm",
    },
    {
      trip_id: "SF-954002",
      route_id: "22",
      start_time: "08:25",
      status: "SCHEDULED",
      reason: "Turnback at Fillmore & 16th without schedule cancellation notice",
    },
    {
      trip_id: "SF-892311",
      route_id: "49",
      start_time: "08:28",
      status: "SCHEDULED",
      reason: "Missing assigned BRT coach on Van Ness transitway",
    },
    {
      trip_id: "SF-931084",
      route_id: "8",
      start_time: "08:31",
      status: "SCHEDULED",
      reason: "No vehicle assigned and no active GPS broadcast on Bayshore corridor",
    },
    {
      trip_id: "SF-874012",
      route_id: "N",
      start_time: "08:35",
      status: "SCHEDULED",
      reason: "Light rail car delayed at Embarcadero portal; transponder offline",
    },
  ],
  coverage_details: {
    agency: "SFMTA (Muni)",
    agency_desc: "San Francisco Municipal Transportation Agency; manages transit, streets, and taxis across the City and County of San Francisco.",
    jurisdiction: "San Francisco, CA",
    jurisdiction_desc: "City and County of San Francisco, California. Dense 49-square-mile transit grid.",
    modes: "Muni Metro Rail, Historic Streetcars (F Market), Cable Cars & Buses",
    modes_desc: "Muni Metro lines (J, K, L, M, N, T), historic F Market streetcars, cable car lines, and 60+ bus and trolleybus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "VehiclePositions & TripUpdates binary feeds served via regional 511.org Open Data API.",
    preset_info: "San Francisco (Muni) Preset",
    preset_info_desc: "CLI supported via `ghost-bus scan --preset sf --api-key YOUR_511_KEY`. Free API key available at 511.org.",
  },
};

export const SF_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 18.4, overall_on_time_pct: 66.8, total_scheduled_trips: 550, total_tracked_vehicles: 449, total_ghost_trips: 101, mean_delay_sec: 168.0 },
  { scan_time: "2026-09-18 18:00:00", ghost_bus_rate_pct: 19.2, overall_on_time_pct: 64.5, total_scheduled_trips: 568, total_tracked_vehicles: 459, total_ghost_trips: 109, mean_delay_sec: 184.2 },
  { scan_time: "2026-09-18 21:00:00", ghost_bus_rate_pct: 15.8, overall_on_time_pct: 71.2, total_scheduled_trips: 490, total_tracked_vehicles: 413, total_ghost_trips: 77, mean_delay_sec: 142.0 },
  { scan_time: "2026-09-19 01:00:00", ghost_bus_rate_pct: 14.1, overall_on_time_pct: 74.5, total_scheduled_trips: 380, total_tracked_vehicles: 326, total_ghost_trips: 54, mean_delay_sec: 120.5 },
  { scan_time: "2026-09-19 06:00:00", ghost_bus_rate_pct: 12.9, overall_on_time_pct: 78.0, total_scheduled_trips: 410, total_tracked_vehicles: 357, total_ghost_trips: 53, mean_delay_sec: 110.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 16.61, overall_on_time_pct: 69.47, total_scheduled_trips: 542, total_tracked_vehicles: 452, total_ghost_trips: 90, mean_delay_sec: 152.4 },
];

export const CHICAGO_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "Chicago Transit Authority (CTA)",
  city: "Chicago, IL",
  transit_system: "CTA",
  region: "Chicagoland / Cook County, Illinois",
  state: "Illinois",
  country: "USA",
  total_scheduled_trips: 612,
  total_tracked_vehicles: 482,
  total_ghost_trips: 130,
  ghost_bus_rate_pct: 21.24,
  vehicle_tracking_rate_pct: 78.76,
  overall_on_time_pct: 64.32,
  delay_distribution: {
    early: 32,
    on_time: 310,
    minor_delay: 105,
    severe_delay: 35,
    ghost: 130,
    canceled: 8,
  },
  mean_delay_sec: 218.0,
  median_delay_sec: 110.0,
  worst_routes_by_ghost: [
    {
      route_id: "79",
      route_name: "79 79th",
      total_trips: 30,
      tracked_vehicles: 16,
      ghost_trips: 14,
      canceled_trips: 2,
      on_time_trips: 9,
      delayed_trips: 7,
      ghost_rate_pct: 46.67,
      on_time_pct: 56.25,
      avg_delay_sec: 372.0,
      max_delay_sec: 840,
    },
    {
      route_id: "66",
      route_name: "66 Chicago",
      total_trips: 28,
      tracked_vehicles: 16,
      ghost_trips: 12,
      canceled_trips: 1,
      on_time_trips: 10,
      delayed_trips: 6,
      ghost_rate_pct: 42.86,
      on_time_pct: 62.5,
      avg_delay_sec: 310.0,
      max_delay_sec: 780,
    },
    {
      route_id: "9",
      route_name: "9 Ashland",
      total_trips: 26,
      tracked_vehicles: 15,
      ghost_trips: 11,
      canceled_trips: 1,
      on_time_trips: 9,
      delayed_trips: 6,
      ghost_rate_pct: 42.31,
      on_time_pct: 60.0,
      avg_delay_sec: 390.0,
      max_delay_sec: 920,
    },
    {
      route_id: "4",
      route_name: "4 Cottage Grove",
      total_trips: 24,
      tracked_vehicles: 15,
      ghost_trips: 9,
      canceled_trips: 0,
      on_time_trips: 10,
      delayed_trips: 5,
      ghost_rate_pct: 37.5,
      on_time_pct: 66.67,
      avg_delay_sec: 270.0,
      max_delay_sec: 650,
    },
    {
      route_id: "49",
      route_name: "49 Western",
      total_trips: 28,
      tracked_vehicles: 18,
      ghost_trips: 10,
      canceled_trips: 1,
      on_time_trips: 11,
      delayed_trips: 7,
      ghost_rate_pct: 35.71,
      on_time_pct: 61.11,
      avg_delay_sec: 342.0,
      max_delay_sec: 790,
    },
    {
      route_id: "X9",
      route_name: "X9 Ashland Express",
      total_trips: 16,
      tracked_vehicles: 11,
      ghost_trips: 5,
      canceled_trips: 0,
      on_time_trips: 8,
      delayed_trips: 3,
      ghost_rate_pct: 31.25,
      on_time_pct: 72.73,
      avg_delay_sec: 198.0,
      max_delay_sec: 480,
    },
    {
      route_id: "22",
      route_name: "22 Clark",
      total_trips: 25,
      tracked_vehicles: 18,
      ghost_trips: 7,
      canceled_trips: 1,
      on_time_trips: 12,
      delayed_trips: 6,
      ghost_rate_pct: 28.0,
      on_time_pct: 66.67,
      avg_delay_sec: 285.0,
      max_delay_sec: 690,
    },
    {
      route_id: "53",
      route_name: "53 Pulaski",
      total_trips: 22,
      tracked_vehicles: 16,
      ghost_trips: 6,
      canceled_trips: 0,
      on_time_trips: 11,
      delayed_trips: 5,
      ghost_rate_pct: 27.27,
      on_time_pct: 68.75,
      avg_delay_sec: 260.0,
      max_delay_sec: 630,
    },
    {
      route_id: "82",
      route_name: "82 Kimball-Homan",
      total_trips: 20,
      tracked_vehicles: 15,
      ghost_trips: 5,
      canceled_trips: 0,
      on_time_trips: 11,
      delayed_trips: 4,
      ghost_rate_pct: 25.0,
      on_time_pct: 73.33,
      avg_delay_sec: 215.0,
      max_delay_sec: 510,
    },
    {
      route_id: "12",
      route_name: "12 Roosevelt",
      total_trips: 18,
      tracked_vehicles: 14,
      ghost_trips: 4,
      canceled_trips: 0,
      on_time_trips: 10,
      delayed_trips: 4,
      ghost_rate_pct: 22.22,
      on_time_pct: 71.43,
      avg_delay_sec: 230.0,
      max_delay_sec: 550,
    },
  ],
  sample_ghost_trips: [
    {
      trip_id: "CTA-410291",
      route_id: "79",
      start_time: "08:12",
      status: "SCHEDULED",
      reason: "Ghost run: bus scheduled at 79th & Western never departed garage",
    },
    {
      trip_id: "CTA-410884",
      route_id: "66",
      start_time: "08:15",
      status: "SCHEDULED",
      reason: "Missing assigned bus; Chicago Ave scheduled departure dropped",
    },
    {
      trip_id: "CTA-411200",
      route_id: "9",
      start_time: "08:20",
      status: "SCHEDULED",
      reason: "Transponder offline on Ashland corridor; no vehicle location reported",
    },
    {
      trip_id: "CTA-412501",
      route_id: "4",
      start_time: "08:24",
      status: "SCHEDULED",
      reason: "Unannounced cut on Cottage Grove; no vehicle assigned",
    },
    {
      trip_id: "CTA-413098",
      route_id: "49",
      start_time: "08:29",
      status: "SCHEDULED",
      reason: "Bus transponder lost at Western & Fullerton",
    },
  ],
  coverage_details: {
    agency: "Chicago Transit Authority (CTA)",
    agency_desc: "Second-largest public transit system in the United States; operates Chicago's heavy rail and bus networks.",
    jurisdiction: "Chicago, IL",
    jurisdiction_desc: "City of Chicago and 35 surrounding suburbs in Cook County, Illinois.",
    modes: "Chicago 'L' Rapid Transit & Urban Buses",
    modes_desc: "8 rapid transit 'L' rail lines (Red, Blue, Brown, Green, Orange, Purple, Pink, Yellow) and 129 bus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Protocol Buffer feeds (`vehiclepositions.pb` & `tripupdates.pb`) via CTA Developer API.",
    preset_info: "Origin of the 'Ghost Bus'",
    preset_info_desc: "Chicago commuters coined 'ghost bus' in 2021-2022 when scheduled buses disappeared from tracking apps. CLI supported via `ghost-bus scan --preset chicago --api-key YOUR_KEY`.",
  },
};

export const CHICAGO_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 23.5, overall_on_time_pct: 61.2, total_scheduled_trips: 620, total_tracked_vehicles: 474, total_ghost_trips: 146, mean_delay_sec: 234.0 },
  { scan_time: "2026-09-18 18:00:00", ghost_bus_rate_pct: 25.1, overall_on_time_pct: 59.8, total_scheduled_trips: 645, total_tracked_vehicles: 483, total_ghost_trips: 162, mean_delay_sec: 258.4 },
  { scan_time: "2026-09-18 21:00:00", ghost_bus_rate_pct: 20.4, overall_on_time_pct: 66.0, total_scheduled_trips: 580, total_tracked_vehicles: 462, total_ghost_trips: 118, mean_delay_sec: 205.0 },
  { scan_time: "2026-09-19 01:00:00", ghost_bus_rate_pct: 18.2, overall_on_time_pct: 70.1, total_scheduled_trips: 420, total_tracked_vehicles: 344, total_ghost_trips: 76, mean_delay_sec: 175.0 },
  { scan_time: "2026-09-19 06:00:00", ghost_bus_rate_pct: 16.5, overall_on_time_pct: 73.4, total_scheduled_trips: 450, total_tracked_vehicles: 376, total_ghost_trips: 74, mean_delay_sec: 160.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 21.24, overall_on_time_pct: 64.32, total_scheduled_trips: 612, total_tracked_vehicles: 482, total_ghost_trips: 130, mean_delay_sec: 218.0 },
];

export const BOSTON_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "MBTA (Boston)",
  city: "Boston, MA",
  transit_system: "MBTA",
  region: "Greater Boston, Massachusetts",
  state: "Massachusetts",
  country: "USA",
  total_scheduled_trips: 490,
  total_tracked_vehicles: 418,
  total_ghost_trips: 72,
  ghost_bus_rate_pct: 14.69,
  vehicle_tracking_rate_pct: 85.31,
  overall_on_time_pct: 74.2,
  delay_distribution: {
    early: 20,
    on_time: 310,
    minor_delay: 70,
    severe_delay: 18,
    ghost: 72,
    canceled: 4,
  },
  mean_delay_sec: 132.0,
  median_delay_sec: 48.0,
  worst_routes_by_ghost: [
    {
      route_id: "1",
      route_name: "1 Harvard - Nubian",
      total_trips: 24,
      tracked_vehicles: 15,
      ghost_trips: 9,
      canceled_trips: 1,
      on_time_trips: 10,
      delayed_trips: 5,
      ghost_rate_pct: 37.5,
      on_time_pct: 66.67,
      avg_delay_sec: 310.0,
      max_delay_sec: 680,
    },
    {
      route_id: "28",
      route_name: "28 Mattapan - Ruggles",
      total_trips: 26,
      tracked_vehicles: 17,
      ghost_trips: 9,
      canceled_trips: 1,
      on_time_trips: 12,
      delayed_trips: 5,
      ghost_rate_pct: 34.62,
      on_time_pct: 70.59,
      avg_delay_sec: 260.0,
      max_delay_sec: 610,
    },
    {
      route_id: "66",
      route_name: "66 Harvard - Nubian via Allston",
      total_trips: 22,
      tracked_vehicles: 15,
      ghost_trips: 7,
      canceled_trips: 0,
      on_time_trips: 9,
      delayed_trips: 6,
      ghost_rate_pct: 31.82,
      on_time_pct: 60.0,
      avg_delay_sec: 375.0,
      max_delay_sec: 820,
    },
    {
      route_id: "39",
      route_name: "39 Forest Hills - Back Bay",
      total_trips: 20,
      tracked_vehicles: 14,
      ghost_trips: 6,
      canceled_trips: 0,
      on_time_trips: 10,
      delayed_trips: 4,
      ghost_rate_pct: 30.0,
      on_time_pct: 71.43,
      avg_delay_sec: 235.0,
      max_delay_sec: 540,
    },
    {
      route_id: "57",
      route_name: "57 Watertown - Kenmore",
      total_trips: 18,
      tracked_vehicles: 13,
      ghost_trips: 5,
      canceled_trips: 0,
      on_time_trips: 9,
      delayed_trips: 4,
      ghost_rate_pct: 27.78,
      on_time_pct: 69.23,
      avg_delay_sec: 250.0,
      max_delay_sec: 590,
    },
    {
      route_id: "111",
      route_name: "111 Chelsea - Haymarket",
      total_trips: 22,
      tracked_vehicles: 16,
      ghost_trips: 6,
      canceled_trips: 1,
      on_time_trips: 12,
      delayed_trips: 4,
      ghost_rate_pct: 27.27,
      on_time_pct: 75.0,
      avg_delay_sec: 195.0,
      max_delay_sec: 480,
    },
    {
      route_id: "77",
      route_name: "77 Arlington Heights - Harvard",
      total_trips: 18,
      tracked_vehicles: 14,
      ghost_trips: 4,
      canceled_trips: 0,
      on_time_trips: 11,
      delayed_trips: 3,
      ghost_rate_pct: 22.22,
      on_time_pct: 78.57,
      avg_delay_sec: 160.0,
      max_delay_sec: 380,
    },
  ],
  sample_ghost_trips: [
    {
      trip_id: "MBTA-512039",
      route_id: "1",
      start_time: "08:15",
      status: "SCHEDULED",
      reason: "Missing bus on Mass Ave corridor between MIT and Harvard",
    },
    {
      trip_id: "MBTA-512844",
      route_id: "28",
      start_time: "08:20",
      status: "SCHEDULED",
      reason: "Unfilled operator trip out of Southampton Garage",
    },
    {
      trip_id: "MBTA-513102",
      route_id: "66",
      start_time: "08:26",
      status: "SCHEDULED",
      reason: "No AVL broadcast on Harvard St in Brookline",
    },
  ],
  coverage_details: {
    agency: "Massachusetts Bay Transportation Authority (MBTA)",
    agency_desc: "Primary public transportation provider across Greater Boston, operating heavy rail, light rail, buses, and ferries.",
    jurisdiction: "Boston, MA",
    jurisdiction_desc: "City of Boston and 175 cities and towns throughout eastern Massachusetts.",
    modes: "Subway, Light Rail, Silver Line BRT & Buses",
    modes_desc: "Red, Orange, Blue subway lines, Green Line light rail, Silver Line BRT, and 170+ surface bus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Publicly accessible open protobuf feeds via MBTA V3 Realtime CDN without API key requirement.",
    preset_info: "Zero-Config Open Feed",
    preset_info_desc: "MBTA requires no API key. CLI supported immediately via `ghost-bus scan --preset boston`.",
  },
};

export const BOSTON_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 16.2, overall_on_time_pct: 71.5, total_scheduled_trips: 500, total_tracked_vehicles: 419, total_ghost_trips: 81, mean_delay_sec: 145.0 },
  { scan_time: "2026-09-18 18:00:00", ghost_bus_rate_pct: 17.5, overall_on_time_pct: 69.2, total_scheduled_trips: 512, total_tracked_vehicles: 422, total_ghost_trips: 90, mean_delay_sec: 160.2 },
  { scan_time: "2026-09-18 21:00:00", ghost_bus_rate_pct: 13.8, overall_on_time_pct: 76.0, total_scheduled_trips: 450, total_tracked_vehicles: 388, total_ghost_trips: 62, mean_delay_sec: 125.0 },
  { scan_time: "2026-09-19 01:00:00", ghost_bus_rate_pct: 11.5, overall_on_time_pct: 81.0, total_scheduled_trips: 340, total_tracked_vehicles: 301, total_ghost_trips: 39, mean_delay_sec: 95.0 },
  { scan_time: "2026-09-19 06:00:00", ghost_bus_rate_pct: 10.2, overall_on_time_pct: 83.5, total_scheduled_trips: 370, total_tracked_vehicles: 332, total_ghost_trips: 38, mean_delay_sec: 90.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 14.69, overall_on_time_pct: 74.2, total_scheduled_trips: 490, total_tracked_vehicles: 418, total_ghost_trips: 72, mean_delay_sec: 132.0 },
];

export const NYC_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "MTA New York City Transit",
  city: "New York, NY",
  transit_system: "MTA",
  region: "New York Metropolitan Area",
  state: "New York",
  country: "USA",
  total_scheduled_trips: 980,
  total_tracked_vehicles: 812,
  total_ghost_trips: 168,
  ghost_bus_rate_pct: 17.14,
  vehicle_tracking_rate_pct: 82.86,
  overall_on_time_pct: 71.85,
  delay_distribution: {
    early: 38,
    on_time: 583,
    minor_delay: 145,
    severe_delay: 46,
    ghost: 168,
    canceled: 12,
  },
  mean_delay_sec: 188.0,
  median_delay_sec: 85.0,
  worst_routes_by_ghost: [
    {
      route_id: "M15-SBS",
      route_name: "M15 Select Bus Service",
      total_trips: 36,
      tracked_vehicles: 22,
      ghost_trips: 14,
      canceled_trips: 2,
      on_time_trips: 15,
      delayed_trips: 7,
      ghost_rate_pct: 38.89,
      on_time_pct: 68.18,
      avg_delay_sec: 320.0,
      max_delay_sec: 760,
    },
    {
      route_id: "B46-SBS",
      route_name: "B46 Select Bus Service",
      total_trips: 34,
      tracked_vehicles: 22,
      ghost_trips: 12,
      canceled_trips: 1,
      on_time_trips: 16,
      delayed_trips: 6,
      ghost_rate_pct: 35.29,
      on_time_pct: 72.73,
      avg_delay_sec: 280.0,
      max_delay_sec: 690,
    },
    {
      route_id: "Bx12-SBS",
      route_name: "Bx12 Select Bus Service",
      total_trips: 32,
      tracked_vehicles: 21,
      ghost_trips: 11,
      canceled_trips: 1,
      on_time_trips: 14,
      delayed_trips: 7,
      ghost_rate_pct: 34.38,
      on_time_pct: 66.67,
      avg_delay_sec: 340.0,
      max_delay_sec: 810,
    },
    {
      route_id: "Q44-SBS",
      route_name: "Q44 Select Bus Service",
      total_trips: 28,
      tracked_vehicles: 19,
      ghost_trips: 9,
      canceled_trips: 0,
      on_time_trips: 13,
      delayed_trips: 6,
      ghost_rate_pct: 32.14,
      on_time_pct: 68.42,
      avg_delay_sec: 295.0,
      max_delay_sec: 700,
    },
    {
      route_id: "M101",
      route_name: "M101 Lexington / Amsterdam",
      total_trips: 26,
      tracked_vehicles: 18,
      ghost_trips: 8,
      canceled_trips: 1,
      on_time_trips: 12,
      delayed_trips: 6,
      ghost_rate_pct: 30.77,
      on_time_pct: 66.67,
      avg_delay_sec: 310.0,
      max_delay_sec: 740,
    },
  ],
  sample_ghost_trips: [
    {
      trip_id: "MTA-810921",
      route_id: "M15-SBS",
      start_time: "08:10",
      status: "SCHEDULED",
      reason: "Select Bus departure dropped at 125th & 1st Ave",
    },
    {
      trip_id: "MTA-811402",
      route_id: "B46-SBS",
      start_time: "08:16",
      status: "SCHEDULED",
      reason: "Missing bus on Utica Ave corridor; transponder offline",
    },
    {
      trip_id: "MTA-812033",
      route_id: "Bx12-SBS",
      start_time: "08:22",
      status: "SCHEDULED",
      reason: "Fordham Rd crosstown trip missing without rider bulletin",
    },
  ],
  coverage_details: {
    agency: "Metropolitan Transportation Authority (MTA)",
    agency_desc: "Largest transit agency in North America, carrying over 5 million daily riders across subway and bus networks.",
    jurisdiction: "New York, NY",
    jurisdiction_desc: "Five Boroughs of New York City (Manhattan, Brooklyn, Queens, Bronx, Staten Island).",
    modes: "Subway, Select Bus Service (SBS) & Express Buses",
    modes_desc: "28 subway lines across 472 stations, plus over 300 local, SBS, and express bus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Protobuf feeds via MTA Data Services with API key authentication.",
    preset_info: "MTA NYC Preset",
    preset_info_desc: "CLI supported via `ghost-bus scan --preset nyc --api-key YOUR_MTA_KEY`. Free API key available at api.mta.info.",
  },
};

export const NYC_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 18.9, overall_on_time_pct: 69.1, total_scheduled_trips: 1010, total_tracked_vehicles: 819, total_ghost_trips: 191, mean_delay_sec: 198.0 },
  { scan_time: "2026-09-18 18:00:00", ghost_bus_rate_pct: 20.4, overall_on_time_pct: 67.3, total_scheduled_trips: 1040, total_tracked_vehicles: 828, total_ghost_trips: 212, mean_delay_sec: 215.0 },
  { scan_time: "2026-09-18 21:00:00", ghost_bus_rate_pct: 16.8, overall_on_time_pct: 73.0, total_scheduled_trips: 920, total_tracked_vehicles: 765, total_ghost_trips: 155, mean_delay_sec: 172.0 },
  { scan_time: "2026-09-19 01:00:00", ghost_bus_rate_pct: 14.5, overall_on_time_pct: 77.2, total_scheduled_trips: 680, total_tracked_vehicles: 581, total_ghost_trips: 99, mean_delay_sec: 140.0 },
  { scan_time: "2026-09-19 06:00:00", ghost_bus_rate_pct: 13.1, overall_on_time_pct: 80.0, total_scheduled_trips: 750, total_tracked_vehicles: 652, total_ghost_trips: 98, mean_delay_sec: 130.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 17.14, overall_on_time_pct: 71.85, total_scheduled_trips: 980, total_tracked_vehicles: 812, total_ghost_trips: 168, mean_delay_sec: 188.0 },
];

export function normalizeCityKey(key) {
  if (!key) return "twin-cities";
  const clean = String(key).toLowerCase().trim().replace(/\s+/g, "-").replace(/_/g, "-");
  return CITY_ALIASES[clean] || "twin-cities";
}

export function getAllCitiesData(liveTwinCitiesLatest = null, liveTwinCitiesHistory = null) {
  const tcLatest = liveTwinCitiesLatest || DEFAULT_LATEST;
  const tcHistory = liveTwinCitiesHistory || DEFAULT_HISTORY;

  const twinCitiesSnapshot = {
    ...tcLatest,
    coverage_details: tcLatest.coverage_details || {
      agency: "Metro Transit",
      agency_desc: "Operating division of the Metropolitan Council; primary transit provider in the Twin Cities region.",
      jurisdiction: "Minneapolis & Saint Paul, MN",
      jurisdiction_desc: "State of Minnesota, USA. Covers Hennepin, Ramsey, Anoka, Carver, Dakota, Scott & Washington counties.",
      modes: "Bus, METRO Light Rail & BRT",
      modes_desc: "METRO Blue & Green Light Rail lines, METRO BRT (A, C, D, Orange, Red lines), and 100+ bus routes.",
      protocol: "GTFS Realtime (GTFS-RT)",
      protocol_desc: "Protocol Buffer feeds (vehiclepositions.pb & tripupdates.pb) via Metro Transit open data.",
      preset_info: "Default Open Feed",
      preset_info_desc: "Open public feed with zero authentication required. Automated git-scraping scans run every 30 minutes.",
    },
  };

  return {
    "twin-cities": {
      id: "twin-cities",
      name: "Twin Cities (Metro Transit)",
      shortName: "Twin Cities",
      agency: "Metro Transit",
      city: "Minneapolis–Saint Paul, MN",
      icon: "🏙️",
      website: "https://www.metrotransit.org",
      latest: twinCitiesSnapshot,
      history: Array.isArray(tcHistory) ? tcHistory : [tcHistory],
    },
    sf: {
      id: "sf",
      name: "San Francisco (SFMTA Muni)",
      shortName: "San Francisco",
      agency: "SFMTA (Muni)",
      city: "San Francisco, CA",
      icon: "🌉",
      website: "https://www.sfmta.com",
      latest: SF_LATEST,
      history: SF_HISTORY,
    },
    chicago: {
      id: "chicago",
      name: "Chicago (CTA)",
      shortName: "Chicago",
      agency: "Chicago Transit Authority",
      city: "Chicago, IL",
      icon: "🌆",
      website: "https://www.transitchicago.com",
      latest: CHICAGO_LATEST,
      history: CHICAGO_HISTORY,
    },
    boston: {
      id: "boston",
      name: "Boston (MBTA)",
      shortName: "Boston",
      agency: "MBTA",
      city: "Boston, MA",
      icon: "🏛️",
      website: "https://www.mbta.com",
      latest: BOSTON_LATEST,
      history: BOSTON_HISTORY,
    },
    nyc: {
      id: "nyc",
      name: "New York (MTA)",
      shortName: "New York",
      agency: "MTA New York City Transit",
      city: "New York, NY",
      icon: "🗽",
      website: "https://new.mta.info",
      latest: NYC_LATEST,
      history: NYC_HISTORY,
    },
  };
}
