/**
 * Multi-city dataset and configuration for Ghost Bus Tracker
 * Supports 13 major North American transit markets:
 * 1. Twin Cities (Metro Transit - Minneapolis–St. Paul)
 * 2. San Francisco (SFMTA Muni)
 * 3. Chicago (CTA)
 * 4. Boston (MBTA)
 * 5. New York City (MTA)
 * 6. Philadelphia (SEPTA)
 * 7. Washington, D.C. (WMATA)
 * 8. Los Angeles (LA Metro)
 * 9. Seattle (Sound Transit & King County Metro)
 * 10. Denver (RTD)
 * 11. Portland (TriMet)
 * 12. Atlanta (MARTA)
 * 13. Toronto (TTC)
 */

import { DEFAULT_LATEST, DEFAULT_HISTORY } from "./snapshot_data.js";

export const CITY_PRESETS = [
  {
    id: "twin-cities",
    name: "Twin Cities (Metro Transit)",
    shortName: "Twin Cities",
    agency: "Metro Transit",
    city: "Minneapolis–Saint Paul, MN",
    icon: "🏙️",
    website: "https://www.metrotransit.org",
  },
  {
    id: "sf",
    name: "San Francisco (SFMTA Muni)",
    shortName: "San Francisco",
    agency: "SFMTA (Muni)",
    city: "San Francisco, CA",
    icon: "🌉",
    website: "https://www.sfmta.com",
  },
  {
    id: "chicago",
    name: "Chicago (CTA)",
    shortName: "Chicago",
    agency: "Chicago Transit Authority",
    city: "Chicago, IL",
    icon: "🌆",
    website: "https://www.transitchicago.com",
  },
  {
    id: "boston",
    name: "Boston (MBTA)",
    shortName: "Boston",
    agency: "MBTA",
    city: "Boston, MA",
    icon: "🏛️",
    website: "https://www.mbta.com",
  },
  {
    id: "nyc",
    name: "New York (MTA)",
    shortName: "New York",
    agency: "MTA New York City Transit",
    city: "New York, NY",
    icon: "🗽",
    website: "https://new.mta.info",
  },
  {
    id: "philly",
    name: "Philadelphia (SEPTA)",
    shortName: "Philadelphia",
    agency: "SEPTA",
    city: "Philadelphia, PA",
    icon: "🔔",
    website: "https://www.septa.org",
  },
  {
    id: "dc",
    name: "Washington, D.C. (WMATA)",
    shortName: "Washington D.C.",
    agency: "WMATA (Metro)",
    city: "Washington, DC",
    icon: "🏛️",
    website: "https://www.wmata.com",
  },
  {
    id: "la",
    name: "Los Angeles (LA Metro)",
    shortName: "Los Angeles",
    agency: "LA Metro",
    city: "Los Angeles, CA",
    icon: "🌴",
    website: "https://www.metro.net",
  },
  {
    id: "seattle",
    name: "Seattle (Sound Transit & KCM)",
    shortName: "Seattle",
    agency: "King County Metro / Sound Transit",
    city: "Seattle, WA",
    icon: "🌲",
    website: "https://kingcounty.gov/metro",
  },
  {
    id: "denver",
    name: "Denver (RTD)",
    shortName: "Denver",
    agency: "RTD",
    city: "Denver, CO",
    icon: "🏔️",
    website: "https://www.rtd-denver.com",
  },
  {
    id: "portland",
    name: "Portland (TriMet)",
    shortName: "Portland",
    agency: "TriMet",
    city: "Portland, OR",
    icon: "🌹",
    website: "https://trimet.org",
  },
  {
    id: "atlanta",
    name: "Atlanta (MARTA)",
    shortName: "Atlanta",
    agency: "MARTA",
    city: "Atlanta, GA",
    icon: "🍑",
    website: "https://www.itsmarta.com",
  },
  {
    id: "toronto",
    name: "Toronto (TTC)",
    shortName: "Toronto",
    agency: "TTC",
    city: "Toronto, ON",
    icon: "🍁",
    website: "https://www.ttc.ca",
  },
];

export const CITY_ALIASES = {
  "twin-cities": "twin-cities",
  "twincities": "twin-cities",
  "mpls": "twin-cities",
  "minneapolis": "twin-cities",
  "stpaul": "twin-cities",
  "st-paul": "twin-cities",
  "msp": "twin-cities",
  "metro-transit": "twin-cities",
  "sf": "sf",
  "sfmta": "sf",
  "muni": "sf",
  "san-francisco": "sf",
  "sanfrancisco": "sf",
  "chicago": "chicago",
  "cta": "chicago",
  "chi": "chicago",
  "boston": "boston",
  "mbta": "boston",
  "nyc": "nyc",
  "mta": "nyc",
  "new-york": "nyc",
  "new-york-city": "nyc",
  "nyct": "nyc",
  "philly": "philly",
  "philadelphia": "philly",
  "septa": "philly",
  "dc": "dc",
  "wmata": "dc",
  "washington": "dc",
  "washington-dc": "dc",
  "metro-dc": "dc",
  "la": "la",
  "lametro": "la",
  "los-angeles": "la",
  "la-metro": "la",
  "losangeles": "la",
  "seattle": "seattle",
  "sound-transit": "seattle",
  "soundtransit": "seattle",
  "kcm": "seattle",
  "king-county-metro": "seattle",
  "denver": "denver",
  "rtd": "denver",
  "portland": "portland",
  "trimet": "portland",
  "pdx": "portland",
  "atlanta": "atlanta",
  "marta": "atlanta",
  "atl": "atlanta",
  "toronto": "toronto",
  "ttc": "toronto",
  "gta": "toronto",
};

export const SF_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "SFMTA (San Francisco Muni)",
  city: "San Francisco, CA",
  transit_system: "SFMTA (Muni)",
  region: "San Francisco Bay Area, California",
  state: "California",
  country: "USA",
  total_scheduled_trips: 542,
  total_tracked_vehicles: 452,
  total_ghost_trips: 90,
  ghost_bus_rate_pct: 16.61,
  vehicle_tracking_rate_pct: 83.39,
  overall_on_time_pct: 69.47,
  delay_distribution: { early: 28, on_time: 314, minor_delay: 84, severe_delay: 26, ghost: 90, canceled: 6 },
  mean_delay_sec: 152.4,
  median_delay_sec: 65.0,
  worst_routes_by_ghost: [
    { route_id: "14R", route_name: "14R Mission Rapid", total_trips: 28, tracked_vehicles: 16, ghost_trips: 12, canceled_trips: 2, on_time_trips: 10, delayed_trips: 6, ghost_rate_pct: 42.86, on_time_pct: 62.5, avg_delay_sec: 288.0, max_delay_sec: 720 },
    { route_id: "38R", route_name: "38R Geary Rapid", total_trips: 32, tracked_vehicles: 20, ghost_trips: 12, canceled_trips: 1, on_time_trips: 14, delayed_trips: 6, ghost_rate_pct: 37.5, on_time_pct: 70.0, avg_delay_sec: 204.0, max_delay_sec: 610 },
    { route_id: "1", route_name: "1 California", total_trips: 18, tracked_vehicles: 12, ghost_trips: 6, canceled_trips: 0, on_time_trips: 8, delayed_trips: 4, ghost_rate_pct: 33.33, on_time_pct: 66.67, avg_delay_sec: 312.0, max_delay_sec: 680 },
    { route_id: "22", route_name: "22 Fillmore", total_trips: 22, tracked_vehicles: 15, ghost_trips: 7, canceled_trips: 1, on_time_trips: 9, delayed_trips: 6, ghost_rate_pct: 31.82, on_time_pct: 60.0, avg_delay_sec: 348.0, max_delay_sec: 780 },
    { route_id: "8", route_name: "8 Bayshore", total_trips: 20, tracked_vehicles: 14, ghost_trips: 6, canceled_trips: 0, on_time_trips: 8, delayed_trips: 6, ghost_rate_pct: 30.0, on_time_pct: 57.14, avg_delay_sec: 420.0, max_delay_sec: 910 },
    { route_id: "49", route_name: "49 Van Ness / Mission", total_trips: 24, tracked_vehicles: 17, ghost_trips: 7, canceled_trips: 0, on_time_trips: 13, delayed_trips: 4, ghost_rate_pct: 29.17, on_time_pct: 76.47, avg_delay_sec: 138.0, max_delay_sec: 420 },
    { route_id: "30", route_name: "30 Stockton", total_trips: 22, tracked_vehicles: 16, ghost_trips: 6, canceled_trips: 1, on_time_trips: 10, delayed_trips: 6, ghost_rate_pct: 27.27, on_time_pct: 62.5, avg_delay_sec: 330.0, max_delay_sec: 660 },
    { route_id: "N", route_name: "N Judah Metro", total_trips: 26, tracked_vehicles: 20, ghost_trips: 6, canceled_trips: 0, on_time_trips: 14, delayed_trips: 6, ghost_rate_pct: 23.08, on_time_pct: 70.0, avg_delay_sec: 210.0, max_delay_sec: 540 },
    { route_id: "T", route_name: "T Third Street Metro", total_trips: 18, tracked_vehicles: 14, ghost_trips: 4, canceled_trips: 0, on_time_trips: 9, delayed_trips: 5, ghost_rate_pct: 22.22, on_time_pct: 64.29, avg_delay_sec: 258.0, max_delay_sec: 590 },
    { route_id: "5R", route_name: "5R Fulton Rapid", total_trips: 16, tracked_vehicles: 13, ghost_trips: 3, canceled_trips: 0, on_time_trips: 10, delayed_trips: 3, ghost_rate_pct: 18.75, on_time_pct: 76.92, avg_delay_sec: 168.0, max_delay_sec: 390 },
  ],
  sample_ghost_trips: [
    { trip_id: "SF-940212", route_id: "14R", start_time: "08:14", status: "SCHEDULED", reason: "No vehicle assigned and no GPS transponder broadcast on Mission St corridor" },
    { trip_id: "SF-881230", route_id: "38R", start_time: "08:19", status: "SCHEDULED", reason: "Assigned coach #6521 dropped transponder signal past Park Presidio" },
    { trip_id: "SF-912044", route_id: "1", start_time: "08:22", status: "SCHEDULED", reason: "Unfilled operator run; vehicle never departed California & Drumm" },
    { trip_id: "SF-954002", route_id: "22", start_time: "08:25", status: "SCHEDULED", reason: "Turnback at Fillmore & 16th without schedule cancellation notice" },
  ],
  coverage_details: {
    agency: "SFMTA (Muni)",
    agency_desc: "San Francisco Municipal Transportation Agency; manages transit, streets, and taxis across the City and County of San Francisco.",
    jurisdiction: "San Francisco, CA",
    jurisdiction_desc: "City and County of San Francisco, California. Dense 49-square-mile transit grid.",
    modes: "Muni Metro Rail, Historic Streetcars (F Market), Cable Cars & Buses",
    modes_desc: "Muni Metro lines (J, K, L, M, N, T), historic F Market streetcars, cable car lines, and 60+ bus and trolleybus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "VehiclePositions & TripUpdates binary feeds served via regional 511.org Open Data API.",
    preset_info: "San Francisco (Muni) Preset",
    preset_info_desc: "CLI supported via `ghost-bus scan --preset sf --api-key YOUR_511_KEY`. Free API key available at 511.org.",
  },
};

export const SF_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 18.4, overall_on_time_pct: 66.8, total_scheduled_trips: 550, total_tracked_vehicles: 449, total_ghost_trips: 101, mean_delay_sec: 168.0 },
  { scan_time: "2026-09-18 18:00:00", ghost_bus_rate_pct: 19.2, overall_on_time_pct: 64.5, total_scheduled_trips: 568, total_tracked_vehicles: 459, total_ghost_trips: 109, mean_delay_sec: 184.2 },
  { scan_time: "2026-09-18 21:00:00", ghost_bus_rate_pct: 15.8, overall_on_time_pct: 71.2, total_scheduled_trips: 490, total_tracked_vehicles: 413, total_ghost_trips: 77, mean_delay_sec: 142.0 },
  { scan_time: "2026-09-19 01:00:00", ghost_bus_rate_pct: 14.1, overall_on_time_pct: 74.5, total_scheduled_trips: 380, total_tracked_vehicles: 326, total_ghost_trips: 54, mean_delay_sec: 120.5 },
  { scan_time: "2026-09-19 06:00:00", ghost_bus_rate_pct: 12.9, overall_on_time_pct: 78.0, total_scheduled_trips: 410, total_tracked_vehicles: 357, total_ghost_trips: 53, mean_delay_sec: 110.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 16.61, overall_on_time_pct: 69.47, total_scheduled_trips: 542, total_tracked_vehicles: 452, total_ghost_trips: 90, mean_delay_sec: 152.4 },
];

export const CHICAGO_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "Chicago Transit Authority (CTA)",
  city: "Chicago, IL",
  transit_system: "CTA",
  region: "Chicagoland / Cook County, Illinois",
  state: "Illinois",
  country: "USA",
  total_scheduled_trips: 612,
  total_tracked_vehicles: 482,
  total_ghost_trips: 130,
  ghost_bus_rate_pct: 21.24,
  vehicle_tracking_rate_pct: 78.76,
  overall_on_time_pct: 64.32,
  delay_distribution: { early: 32, on_time: 310, minor_delay: 105, severe_delay: 35, ghost: 130, canceled: 8 },
  mean_delay_sec: 218.0,
  median_delay_sec: 110.0,
  worst_routes_by_ghost: [
    { route_id: "79", route_name: "79 79th", total_trips: 30, tracked_vehicles: 16, ghost_trips: 14, canceled_trips: 2, on_time_trips: 9, delayed_trips: 7, ghost_rate_pct: 46.67, on_time_pct: 56.25, avg_delay_sec: 372.0, max_delay_sec: 840 },
    { route_id: "66", route_name: "66 Chicago", total_trips: 28, tracked_vehicles: 16, ghost_trips: 12, canceled_trips: 1, on_time_trips: 10, delayed_trips: 6, ghost_rate_pct: 42.86, on_time_pct: 62.5, avg_delay_sec: 310.0, max_delay_sec: 780 },
    { route_id: "9", route_name: "9 Ashland", total_trips: 26, tracked_vehicles: 15, ghost_trips: 11, canceled_trips: 1, on_time_trips: 9, delayed_trips: 6, ghost_rate_pct: 42.31, on_time_pct: 60.0, avg_delay_sec: 390.0, max_delay_sec: 920 },
    { route_id: "4", route_name: "4 Cottage Grove", total_trips: 24, tracked_vehicles: 15, ghost_trips: 9, canceled_trips: 0, on_time_trips: 10, delayed_trips: 5, ghost_rate_pct: 37.5, on_time_pct: 66.67, avg_delay_sec: 270.0, max_delay_sec: 650 },
    { route_id: "49", route_name: "49 Western", total_trips: 28, tracked_vehicles: 18, ghost_trips: 10, canceled_trips: 1, on_time_trips: 11, delayed_trips: 7, ghost_rate_pct: 35.71, on_time_pct: 61.11, avg_delay_sec: 342.0, max_delay_sec: 790 },
  ],
  sample_ghost_trips: [
    { trip_id: "CTA-410291", route_id: "79", start_time: "08:12", status: "SCHEDULED", reason: "Ghost run: bus scheduled at 79th & Western never departed garage" },
    { trip_id: "CTA-410884", route_id: "66", start_time: "08:15", status: "SCHEDULED", reason: "Missing assigned bus; Chicago Ave scheduled departure dropped" },
  ],
  coverage_details: {
    agency: "Chicago Transit Authority (CTA)",
    agency_desc: "Second-largest public transit system in the United States; operates Chicago's heavy rail and bus networks.",
    jurisdiction: "Chicago, IL",
    jurisdiction_desc: "City of Chicago and 35 surrounding suburbs in Cook County, Illinois.",
    modes: "Chicago 'L' Rapid Transit & Urban Buses",
    modes_desc: "8 rapid transit 'L' rail lines (Red, Blue, Brown, Green, Orange, Purple, Pink, Yellow) and 129 bus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Protocol Buffer feeds (`vehiclepositions.pb` & `tripupdates.pb`) via CTA Developer API.",
    preset_info: "Origin of the 'Ghost Bus'",
    preset_info_desc: "Chicago commuters coined 'ghost bus' in 2021-2022 when scheduled buses disappeared from tracking apps.",
  },
};

export const CHICAGO_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 23.5, overall_on_time_pct: 61.2, total_scheduled_trips: 620, total_tracked_vehicles: 474, total_ghost_trips: 146, mean_delay_sec: 234.0 },
  { scan_time: "2026-09-18 18:00:00", ghost_bus_rate_pct: 25.1, overall_on_time_pct: 59.8, total_scheduled_trips: 645, total_tracked_vehicles: 483, total_ghost_trips: 162, mean_delay_sec: 258.4 },
  { scan_time: "2026-09-18 21:00:00", ghost_bus_rate_pct: 20.4, overall_on_time_pct: 66.0, total_scheduled_trips: 580, total_tracked_vehicles: 462, total_ghost_trips: 118, mean_delay_sec: 205.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 21.24, overall_on_time_pct: 64.32, total_scheduled_trips: 612, total_tracked_vehicles: 482, total_ghost_trips: 130, mean_delay_sec: 218.0 },
];

export const BOSTON_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "MBTA (Boston)",
  city: "Boston, MA",
  transit_system: "MBTA",
  region: "Greater Boston, Massachusetts",
  state: "Massachusetts",
  country: "USA",
  total_scheduled_trips: 490,
  total_tracked_vehicles: 418,
  total_ghost_trips: 72,
  ghost_bus_rate_pct: 14.69,
  vehicle_tracking_rate_pct: 85.31,
  overall_on_time_pct: 74.2,
  delay_distribution: { early: 20, on_time: 310, minor_delay: 70, severe_delay: 18, ghost: 72, canceled: 4 },
  mean_delay_sec: 132.0,
  median_delay_sec: 48.0,
  worst_routes_by_ghost: [
    { route_id: "1", route_name: "1 Harvard - Nubian", total_trips: 24, tracked_vehicles: 15, ghost_trips: 9, canceled_trips: 1, on_time_trips: 10, delayed_trips: 5, ghost_rate_pct: 37.5, on_time_pct: 66.67, avg_delay_sec: 310.0, max_delay_sec: 680 },
    { route_id: "28", route_name: "28 Mattapan - Ruggles", total_trips: 26, tracked_vehicles: 17, ghost_trips: 9, canceled_trips: 1, on_time_trips: 12, delayed_trips: 5, ghost_rate_pct: 34.62, on_time_pct: 70.59, avg_delay_sec: 260.0, max_delay_sec: 610 },
    { route_id: "66", route_name: "66 Harvard - Nubian via Allston", total_trips: 22, tracked_vehicles: 15, ghost_trips: 7, canceled_trips: 0, on_time_trips: 9, delayed_trips: 6, ghost_rate_pct: 31.82, on_time_pct: 60.0, avg_delay_sec: 375.0, max_delay_sec: 820 },
  ],
  sample_ghost_trips: [
    { trip_id: "MBTA-512039", route_id: "1", start_time: "08:15", status: "SCHEDULED", reason: "Missing bus on Mass Ave corridor between MIT and Harvard" },
  ],
  coverage_details: {
    agency: "Massachusetts Bay Transportation Authority (MBTA)",
    agency_desc: "Primary public transportation provider across Greater Boston.",
    jurisdiction: "Boston, MA",
    jurisdiction_desc: "City of Boston and 175 cities and towns throughout eastern Massachusetts.",
    modes: "Subway, Light Rail, Silver Line BRT & Buses",
    modes_desc: "Red, Orange, Blue subway lines, Green Line light rail, Silver Line BRT, and 170+ surface bus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Publicly accessible open protobuf feeds via MBTA V3 Realtime CDN.",
    preset_info: "Zero-Config Open Feed",
    preset_info_desc: "MBTA requires no API key. CLI supported immediately via `ghost-bus scan --preset boston`.",
  },
};

export const BOSTON_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 16.2, overall_on_time_pct: 71.5, total_scheduled_trips: 500, total_tracked_vehicles: 419, total_ghost_trips: 81, mean_delay_sec: 145.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 14.69, overall_on_time_pct: 74.2, total_scheduled_trips: 490, total_tracked_vehicles: 418, total_ghost_trips: 72, mean_delay_sec: 132.0 },
];

export const NYC_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "MTA New York City Transit",
  city: "New York, NY",
  transit_system: "MTA",
  region: "New York Metropolitan Area",
  state: "New York",
  country: "USA",
  total_scheduled_trips: 980,
  total_tracked_vehicles: 812,
  total_ghost_trips: 168,
  ghost_bus_rate_pct: 17.14,
  vehicle_tracking_rate_pct: 82.86,
  overall_on_time_pct: 71.85,
  delay_distribution: { early: 38, on_time: 583, minor_delay: 145, severe_delay: 46, ghost: 168, canceled: 12 },
  mean_delay_sec: 188.0,
  median_delay_sec: 85.0,
  worst_routes_by_ghost: [
    { route_id: "M15-SBS", route_name: "M15 Select Bus Service", total_trips: 36, tracked_vehicles: 22, ghost_trips: 14, canceled_trips: 2, on_time_trips: 15, delayed_trips: 7, ghost_rate_pct: 38.89, on_time_pct: 68.18, avg_delay_sec: 320.0, max_delay_sec: 760 },
    { route_id: "B46-SBS", route_name: "B46 Select Bus Service", total_trips: 34, tracked_vehicles: 22, ghost_trips: 12, canceled_trips: 1, on_time_trips: 16, delayed_trips: 6, ghost_rate_pct: 35.29, on_time_pct: 72.73, avg_delay_sec: 280.0, max_delay_sec: 690 },
    { route_id: "Bx12-SBS", route_name: "Bx12 Select Bus Service", total_trips: 32, tracked_vehicles: 21, ghost_trips: 11, canceled_trips: 1, on_time_trips: 14, delayed_trips: 7, ghost_rate_pct: 34.38, on_time_pct: 66.67, avg_delay_sec: 340.0, max_delay_sec: 810 },
  ],
  sample_ghost_trips: [
    { trip_id: "MTA-810921", route_id: "M15-SBS", start_time: "08:10", status: "SCHEDULED", reason: "Select Bus departure dropped at 125th & 1st Ave" },
  ],
  coverage_details: {
    agency: "Metropolitan Transportation Authority (MTA)",
    agency_desc: "Largest transit agency in North America, carrying over 5 million daily riders.",
    jurisdiction: "New York, NY",
    jurisdiction_desc: "Five Boroughs of New York City.",
    modes: "Subway, Select Bus Service (SBS) & Express Buses",
    modes_desc: "28 subway lines across 472 stations, plus over 300 local, SBS, and express bus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Protobuf feeds via MTA Data Services with API key authentication.",
    preset_info: "MTA NYC Preset",
    preset_info_desc: "CLI supported via `ghost-bus scan --preset nyc --api-key YOUR_MTA_KEY`.",
  },
};

export const NYC_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 18.9, overall_on_time_pct: 69.1, total_scheduled_trips: 1010, total_tracked_vehicles: 819, total_ghost_trips: 191, mean_delay_sec: 198.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 17.14, overall_on_time_pct: 71.85, total_scheduled_trips: 980, total_tracked_vehicles: 812, total_ghost_trips: 168, mean_delay_sec: 188.0 },
];

export const PHILLY_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "SEPTA (Philadelphia)",
  city: "Philadelphia, PA",
  transit_system: "SEPTA",
  region: "Greater Philadelphia / Delaware Valley, Pennsylvania",
  state: "Pennsylvania",
  country: "USA",
  total_scheduled_trips: 580,
  total_tracked_vehicles: 465,
  total_ghost_trips: 115,
  ghost_bus_rate_pct: 19.83,
  vehicle_tracking_rate_pct: 80.17,
  overall_on_time_pct: 65.8,
  delay_distribution: { early: 25, on_time: 290, minor_delay: 96, severe_delay: 34, ghost: 115, canceled: 10 },
  mean_delay_sec: 194.0,
  median_delay_sec: 90.0,
  worst_routes_by_ghost: [
    { route_id: "23", route_name: "Route 23 Germantown Ave", total_trips: 26, tracked_vehicles: 14, ghost_trips: 12, canceled_trips: 2, on_time_trips: 8, delayed_trips: 6, ghost_rate_pct: 46.15, on_time_pct: 57.14, avg_delay_sec: 340.0, max_delay_sec: 780 },
    { route_id: "47", route_name: "Route 47 7th & 8th", total_trips: 24, tracked_vehicles: 14, ghost_trips: 10, canceled_trips: 1, on_time_trips: 9, delayed_trips: 5, ghost_rate_pct: 41.67, on_time_pct: 64.29, avg_delay_sec: 310.0, max_delay_sec: 720 },
    { route_id: "52", route_name: "Route 52 52nd St", total_trips: 22, tracked_vehicles: 14, ghost_trips: 8, canceled_trips: 0, on_time_trips: 8, delayed_trips: 6, ghost_rate_pct: 36.36, on_time_pct: 57.14, avg_delay_sec: 365.0, max_delay_sec: 810 },
    { route_id: "MFL", route_name: "Market-Frankford Line", total_trips: 30, tracked_vehicles: 22, ghost_trips: 8, canceled_trips: 1, on_time_trips: 16, delayed_trips: 6, ghost_rate_pct: 26.67, on_time_pct: 72.73, avg_delay_sec: 180.0, max_delay_sec: 450 },
    { route_id: "BSL", route_name: "Broad Street Line", total_trips: 28, tracked_vehicles: 22, ghost_trips: 6, canceled_trips: 0, on_time_trips: 17, delayed_trips: 5, ghost_rate_pct: 21.43, on_time_pct: 77.27, avg_delay_sec: 145.0, max_delay_sec: 390 },
  ],
  sample_ghost_trips: [
    { trip_id: "SEPTA-230911", route_id: "23", start_time: "08:12", status: "SCHEDULED", reason: "Bus transponder dropped along Germantown Ave corridor" },
    { trip_id: "SEPTA-471204", route_id: "47", start_time: "08:18", status: "SCHEDULED", reason: "Unassigned operator trip out of Callowhill District" },
  ],
  coverage_details: {
    agency: "SEPTA (Philadelphia)",
    agency_desc: "Southeastern Pennsylvania Transportation Authority; serves Philadelphia, Bucks, Chester, Delaware, and Montgomery counties.",
    jurisdiction: "Philadelphia, PA",
    jurisdiction_desc: "Greater Philadelphia / Delaware Valley region.",
    modes: "Subway, Trolley & 120+ Bus Routes",
    modes_desc: "Broad Street & Market-Frankford heavy rail, historic trolley lines, Norristown High Speed Line, and regional bus grid.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Open GTFS-RT feeds via SEPTA Open Data developer portal.",
    preset_info: "Open GTFS-RT Feed",
    preset_info_desc: "No API key required. CLI supported via `ghost-bus scan --preset philly`.",
  },
};

export const PHILLY_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 21.5, overall_on_time_pct: 63.2, total_scheduled_trips: 590, total_tracked_vehicles: 463, total_ghost_trips: 127, mean_delay_sec: 210.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 19.83, overall_on_time_pct: 65.8, total_scheduled_trips: 580, total_tracked_vehicles: 465, total_ghost_trips: 115, mean_delay_sec: 194.0 },
];

export const DC_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "WMATA (Washington D.C.)",
  city: "Washington, DC",
  transit_system: "WMATA",
  region: "Washington Metropolitan Area (DC, MD, VA)",
  state: "District of Columbia",
  country: "USA",
  total_scheduled_trips: 640,
  total_tracked_vehicles: 524,
  total_ghost_trips: 116,
  ghost_bus_rate_pct: 18.13,
  vehicle_tracking_rate_pct: 81.87,
  overall_on_time_pct: 70.42,
  delay_distribution: { early: 30, on_time: 345, minor_delay: 110, severe_delay: 29, ghost: 116, canceled: 10 },
  mean_delay_sec: 168.0,
  median_delay_sec: 75.0,
  worst_routes_by_ghost: [
    { route_id: "S2", route_name: "Route S2 16th Street Line", total_trips: 32, tracked_vehicles: 19, ghost_trips: 13, canceled_trips: 2, on_time_trips: 12, delayed_trips: 7, ghost_rate_pct: 40.63, on_time_pct: 63.16, avg_delay_sec: 295.0, max_delay_sec: 680 },
    { route_id: "70", route_name: "Route 70 Georgia Avenue Line", total_trips: 28, tracked_vehicles: 18, ghost_trips: 10, canceled_trips: 1, on_time_trips: 11, delayed_trips: 7, ghost_rate_pct: 35.71, on_time_pct: 61.11, avg_delay_sec: 320.0, max_delay_sec: 740 },
    { route_id: "X2", route_name: "Route X2 Benning Rd-H St", total_trips: 26, tracked_vehicles: 17, ghost_trips: 9, canceled_trips: 1, on_time_trips: 10, delayed_trips: 7, ghost_rate_pct: 34.62, on_time_pct: 58.82, avg_delay_sec: 350.0, max_delay_sec: 790 },
    { route_id: "33", route_name: "Route 33 Wisconsin Avenue", total_trips: 24, tracked_vehicles: 17, ghost_trips: 7, canceled_trips: 0, on_time_trips: 12, delayed_trips: 5, ghost_rate_pct: 29.17, on_time_pct: 70.59, avg_delay_sec: 215.0, max_delay_sec: 520 },
    { route_id: "RED", route_name: "Metrorail Red Line", total_trips: 34, tracked_vehicles: 29, ghost_trips: 5, canceled_trips: 0, on_time_trips: 25, delayed_trips: 4, ghost_rate_pct: 14.71, on_time_pct: 86.21, avg_delay_sec: 95.0, max_delay_sec: 280 },
  ],
  sample_ghost_trips: [
    { trip_id: "WMATA-9104", route_id: "S2", start_time: "08:14", status: "SCHEDULED", reason: "Metrobus dropped tracking transponder north of Columbia Heights" },
    { trip_id: "WMATA-7019", route_id: "70", start_time: "08:21", status: "SCHEDULED", reason: "Unfilled run at Silver Spring transit center" },
  ],
  coverage_details: {
    agency: "Washington Metropolitan Area Transit Authority (WMATA)",
    agency_desc: "Joint transit agency serving the District of Columbia, suburban Maryland, and Northern Virginia.",
    jurisdiction: "Washington, DC",
    jurisdiction_desc: "Capital region spanning DC, Montgomery, Prince George's, Fairfax, and Arlington counties.",
    modes: "Metrorail & Metrobus Fleet",
    modes_desc: "6 Metrorail lines (Red, Orange, Silver, Blue, Yellow, Green) and over 1,500 Metrobus vehicles.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Protobuf feeds via WMATA Developer API with API key authentication.",
    preset_info: "WMATA API Preset",
    preset_info_desc: "CLI supported via `ghost-bus scan --preset dc --api-key YOUR_WMATA_KEY`.",
  },
};

export const DC_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 19.8, overall_on_time_pct: 68.2, total_scheduled_trips: 650, total_tracked_vehicles: 521, total_ghost_trips: 129, mean_delay_sec: 180.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 18.13, overall_on_time_pct: 70.42, total_scheduled_trips: 640, total_tracked_vehicles: 524, total_ghost_trips: 116, mean_delay_sec: 168.0 },
];

export const LA_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "LA Metro (Los Angeles)",
  city: "Los Angeles, CA",
  transit_system: "LA Metro",
  region: "Los Angeles County, California",
  state: "California",
  country: "USA",
  total_scheduled_trips: 890,
  total_tracked_vehicles: 735,
  total_ghost_trips: 155,
  ghost_bus_rate_pct: 17.42,
  vehicle_tracking_rate_pct: 82.58,
  overall_on_time_pct: 67.2,
  delay_distribution: { early: 42, on_time: 480, minor_delay: 158, severe_delay: 45, ghost: 155, canceled: 10 },
  mean_delay_sec: 210.0,
  median_delay_sec: 95.0,
  worst_routes_by_ghost: [
    { route_id: "720", route_name: "Line 720 Wilshire Rapid", total_trips: 38, tracked_vehicles: 23, ghost_trips: 15, canceled_trips: 2, on_time_trips: 14, delayed_trips: 9, ghost_rate_pct: 39.47, on_time_pct: 60.87, avg_delay_sec: 360.0, max_delay_sec: 840 },
    { route_id: "204", route_name: "Line 204 Vermont Ave", total_trips: 34, tracked_vehicles: 22, ghost_trips: 12, canceled_trips: 1, on_time_trips: 13, delayed_trips: 9, ghost_rate_pct: 35.29, on_time_pct: 59.09, avg_delay_sec: 385.0, max_delay_sec: 890 },
    { route_id: "207", route_name: "Line 207 Western Ave", total_trips: 32, tracked_vehicles: 21, ghost_trips: 11, canceled_trips: 1, on_time_trips: 14, delayed_trips: 7, ghost_rate_pct: 34.38, on_time_pct: 66.67, avg_delay_sec: 330.0, max_delay_sec: 760 },
    { route_id: "4", route_name: "Line 4 Santa Monica Blvd", total_trips: 28, tracked_vehicles: 19, ghost_trips: 9, canceled_trips: 0, on_time_trips: 13, delayed_trips: 6, ghost_rate_pct: 32.14, on_time_pct: 68.42, avg_delay_sec: 290.0, max_delay_sec: 670 },
    { route_id: "B-LINE", route_name: "Metro B Line (Subway)", total_trips: 30, tracked_vehicles: 26, ghost_trips: 4, canceled_trips: 0, on_time_trips: 22, delayed_trips: 4, ghost_rate_pct: 13.33, on_time_pct: 84.62, avg_delay_sec: 110.0, max_delay_sec: 290 },
  ],
  sample_ghost_trips: [
    { trip_id: "LAM-72081", route_id: "720", start_time: "08:15", status: "SCHEDULED", reason: "Articulated coach dropped tracking transponder on Wilshire corridor" },
    { trip_id: "LAM-20412", route_id: "204", start_time: "08:22", status: "SCHEDULED", reason: "Unassigned trip at Vermont/Athens terminal" },
  ],
  coverage_details: {
    agency: "Los Angeles County Metropolitan Transportation Authority",
    agency_desc: "Main transit planner and operator for 1,433 square miles of Los Angeles County.",
    jurisdiction: "Los Angeles, CA",
    jurisdiction_desc: "Los Angeles County, California.",
    modes: "Metro Rail (6 Lines) & 2,200+ Buses",
    modes_desc: "A, B, C, D, E, K rail lines, Metro G Line (Orange BRT), Metro J Line (Silver BRT), and extensive bus network.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Publicly accessible protobuf feeds via api.metro.net.",
    preset_info: "Open GTFS-RT Feed",
    preset_info_desc: "No API key required. CLI supported via `ghost-bus scan --preset la`.",
  },
};

export const LA_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 19.1, overall_on_time_pct: 65.0, total_scheduled_trips: 910, total_tracked_vehicles: 736, total_ghost_trips: 174, mean_delay_sec: 225.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 17.42, overall_on_time_pct: 67.2, total_scheduled_trips: 890, total_tracked_vehicles: 735, total_ghost_trips: 155, mean_delay_sec: 210.0 },
];

export const SEATTLE_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "King County Metro / Sound Transit",
  city: "Seattle, WA",
  transit_system: "Sound Transit & KCM",
  region: "Central Puget Sound Region, Washington",
  state: "Washington",
  country: "USA",
  total_scheduled_trips: 620,
  total_tracked_vehicles: 532,
  total_ghost_trips: 88,
  ghost_bus_rate_pct: 14.19,
  vehicle_tracking_rate_pct: 85.81,
  overall_on_time_pct: 75.3,
  delay_distribution: { early: 28, on_time: 395, minor_delay: 86, severe_delay: 23, ghost: 88, canceled: 8 },
  mean_delay_sec: 135.0,
  median_delay_sec: 50.0,
  worst_routes_by_ghost: [
    { route_id: "RR-E", route_name: "RapidRide E Line (Aurora)", total_trips: 34, tracked_vehicles: 23, ghost_trips: 11, canceled_trips: 1, on_time_trips: 16, delayed_trips: 7, ghost_rate_pct: 32.35, on_time_pct: 69.57, avg_delay_sec: 245.0, max_delay_sec: 590 },
    { route_id: "7", route_name: "Route 7 Rainier Ave", total_trips: 28, tracked_vehicles: 20, ghost_trips: 8, canceled_trips: 1, on_time_trips: 13, delayed_trips: 7, ghost_rate_pct: 28.57, on_time_pct: 65.0, avg_delay_sec: 270.0, max_delay_sec: 640 },
    { route_id: "RR-D", route_name: "RapidRide D Line (Ballard)", total_trips: 30, tracked_vehicles: 22, ghost_trips: 8, canceled_trips: 0, on_time_trips: 16, delayed_trips: 6, ghost_rate_pct: 26.67, on_time_pct: 72.73, avg_delay_sec: 220.0, max_delay_sec: 530 },
    { route_id: "44", route_name: "Route 44 Ballard-UW", total_trips: 22, tracked_vehicles: 17, ghost_trips: 5, canceled_trips: 0, on_time_trips: 12, delayed_trips: 5, ghost_rate_pct: 22.73, on_time_pct: 70.59, avg_delay_sec: 210.0, max_delay_sec: 490 },
    { route_id: "LINK-1", route_name: "Sound Transit 1 Line", total_trips: 32, tracked_vehicles: 28, ghost_trips: 4, canceled_trips: 0, on_time_trips: 25, delayed_trips: 3, ghost_rate_pct: 12.5, on_time_pct: 89.29, avg_delay_sec: 85.0, max_delay_sec: 220 },
  ],
  sample_ghost_trips: [
    { trip_id: "KCM-67102", route_id: "RR-E", start_time: "08:10", status: "SCHEDULED", reason: "Bus transponder dropped north of Green Lake on Aurora Ave" },
    { trip_id: "KCM-70192", route_id: "7", start_time: "08:18", status: "SCHEDULED", reason: "Unassigned trolleybus run at Mt Baker transit center" },
  ],
  coverage_details: {
    agency: "King County Metro / Sound Transit",
    agency_desc: "Regional transit coordination across King, Pierce, and Snohomish counties.",
    jurisdiction: "Seattle, WA",
    jurisdiction_desc: "Central Puget Sound metropolitan area.",
    modes: "Link Light Rail, RapidRide & Regional Buses",
    modes_desc: "Link 1 and 2 Lines, Sounder commuter rail, RapidRide bus rapid transit lines (A through H), and 200+ local routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Open public feeds via soundtransit.org and OneBusAway APIs.",
    preset_info: "Open GTFS-RT Feed",
    preset_info_desc: "No API key required. CLI supported via `ghost-bus scan --preset seattle`.",
  },
};

export const SEATTLE_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 15.8, overall_on_time_pct: 73.1, total_scheduled_trips: 630, total_tracked_vehicles: 530, total_ghost_trips: 100, mean_delay_sec: 148.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 14.19, overall_on_time_pct: 75.3, total_scheduled_trips: 620, total_tracked_vehicles: 532, total_ghost_trips: 88, mean_delay_sec: 135.0 },
];

export const DENVER_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "RTD (Denver)",
  city: "Denver, CO",
  transit_system: "RTD",
  region: "Denver Metropolitan Area, Colorado",
  state: "Colorado",
  country: "USA",
  total_scheduled_trips: 460,
  total_tracked_vehicles: 372,
  total_ghost_trips: 88,
  ghost_bus_rate_pct: 19.13,
  vehicle_tracking_rate_pct: 80.87,
  overall_on_time_pct: 68.4,
  delay_distribution: { early: 20, on_time: 252, minor_delay: 82, severe_delay: 18, ghost: 88, canceled: 6 },
  mean_delay_sec: 165.0,
  median_delay_sec: 70.0,
  worst_routes_by_ghost: [
    { route_id: "15", route_name: "Route 15 / 15L Colfax Ave", total_trips: 30, tracked_vehicles: 18, ghost_trips: 12, canceled_trips: 2, on_time_trips: 11, delayed_trips: 7, ghost_rate_pct: 40.0, on_time_pct: 61.11, avg_delay_sec: 310.0, max_delay_sec: 720 },
    { route_id: "0", route_name: "Route 0 South Broadway", total_trips: 24, tracked_vehicles: 15, ghost_trips: 9, canceled_trips: 1, on_time_trips: 10, delayed_trips: 5, ghost_rate_pct: 37.5, on_time_pct: 66.67, avg_delay_sec: 275.0, max_delay_sec: 640 },
    { route_id: "FF1", route_name: "Flatiron Flyer (Denver-Boulder)", total_trips: 22, tracked_vehicles: 16, ghost_trips: 6, canceled_trips: 0, on_time_trips: 12, delayed_trips: 4, ghost_rate_pct: 27.27, on_time_pct: 75.0, avg_delay_sec: 190.0, max_delay_sec: 480 },
  ],
  sample_ghost_trips: [
    { trip_id: "RTD-1508", route_id: "15", start_time: "08:12", status: "SCHEDULED", reason: "Unfilled driver assignment on East Colfax corridor" },
  ],
  coverage_details: {
    agency: "Regional Transportation District (RTD)",
    agency_desc: "Public transit provider across 8 counties in the Denver-Aurora-Boulder metropolitan area.",
    jurisdiction: "Denver, CO",
    jurisdiction_desc: "Denver metropolitan area and Colorado Front Range.",
    modes: "Commuter Rail, Light Rail & Bus Fleet",
    modes_desc: "A, B, G, N commuter rail lines, light rail network, and Flatiron Flyer express bus system.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Public feeds available on rtd-denver.com.",
    preset_info: "Open GTFS-RT Feed",
    preset_info_desc: "No API key required. CLI supported via `ghost-bus scan --preset denver`.",
  },
};

export const DENVER_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 20.8, overall_on_time_pct: 66.5, total_scheduled_trips: 470, total_tracked_vehicles: 372, total_ghost_trips: 98, mean_delay_sec: 178.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 19.13, overall_on_time_pct: 68.4, total_scheduled_trips: 460, total_tracked_vehicles: 372, total_ghost_trips: 88, mean_delay_sec: 165.0 },
];

export const PORTLAND_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "TriMet (Portland)",
  city: "Portland, OR",
  transit_system: "TriMet",
  region: "Portland Metropolitan Area, Oregon",
  state: "Oregon",
  country: "USA",
  total_scheduled_trips: 430,
  total_tracked_vehicles: 368,
  total_ghost_trips: 62,
  ghost_bus_rate_pct: 14.42,
  vehicle_tracking_rate_pct: 85.58,
  overall_on_time_pct: 76.5,
  delay_distribution: { early: 18, on_time: 278, minor_delay: 58, severe_delay: 14, ghost: 62, canceled: 4 },
  mean_delay_sec: 122.0,
  median_delay_sec: 45.0,
  worst_routes_by_ghost: [
    { route_id: "4", route_name: "Line 4 Division/Fessenden", total_trips: 24, tracked_vehicles: 16, ghost_trips: 8, canceled_trips: 1, on_time_trips: 11, delayed_trips: 5, ghost_rate_pct: 33.33, on_time_pct: 68.75, avg_delay_sec: 250.0, max_delay_sec: 610 },
    { route_id: "72", route_name: "Line 72 Killingsworth/82nd", total_trips: 26, tracked_vehicles: 18, ghost_trips: 8, canceled_trips: 1, on_time_trips: 12, delayed_trips: 6, ghost_rate_pct: 30.77, on_time_pct: 66.67, avg_delay_sec: 275.0, max_delay_sec: 650 },
    { route_id: "MAX-BLUE", route_name: "MAX Blue Line", total_trips: 28, tracked_vehicles: 24, ghost_trips: 4, canceled_trips: 0, on_time_trips: 21, delayed_trips: 3, ghost_rate_pct: 14.29, on_time_pct: 87.5, avg_delay_sec: 80.0, max_delay_sec: 210 },
  ],
  sample_ghost_trips: [
    { trip_id: "TRM-4011", route_id: "4", start_time: "08:14", status: "SCHEDULED", reason: "Bus transponder dropped near SE 82nd & Division" },
  ],
  coverage_details: {
    agency: "Tri-County Metropolitan Transportation District of Oregon (TriMet)",
    agency_desc: "Transit operator across the Portland tri-county metropolitan area. Original co-creator of the GTFS standard with Google.",
    jurisdiction: "Portland, OR",
    jurisdiction_desc: "Multnomah, Washington, and Clackamas counties in Oregon.",
    modes: "MAX Light Rail, WES Commuter Rail & Buses",
    modes_desc: "5 MAX light rail lines (Blue, Green, Red, Yellow, Orange), Portland Streetcar, and 85+ bus lines.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Rich GTFS-RT APIs via developer.trimet.org with App ID.",
    preset_info: "TriMet Developer Preset",
    preset_info_desc: "CLI supported via `ghost-bus scan --preset portland --api-key YOUR_APP_ID`.",
  },
};

export const PORTLAND_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 15.6, overall_on_time_pct: 74.8, total_scheduled_trips: 440, total_tracked_vehicles: 371, total_ghost_trips: 69, mean_delay_sec: 135.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 14.42, overall_on_time_pct: 76.5, total_scheduled_trips: 430, total_tracked_vehicles: 368, total_ghost_trips: 62, mean_delay_sec: 122.0 },
];

export const ATLANTA_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "MARTA (Atlanta)",
  city: "Atlanta, GA",
  transit_system: "MARTA",
  region: "Metro Atlanta (Fulton, DeKalb, Clayton Counties), Georgia",
  state: "Georgia",
  country: "USA",
  total_scheduled_trips: 510,
  total_tracked_vehicles: 405,
  total_ghost_trips: 105,
  ghost_bus_rate_pct: 20.59,
  vehicle_tracking_rate_pct: 79.41,
  overall_on_time_pct: 66.2,
  delay_distribution: { early: 22, on_time: 265, minor_delay: 94, severe_delay: 24, ghost: 105, canceled: 8 },
  mean_delay_sec: 185.0,
  median_delay_sec: 80.0,
  worst_routes_by_ghost: [
    { route_id: "83", route_name: "Route 83 Campbellton Rd", total_trips: 26, tracked_vehicles: 15, ghost_trips: 11, canceled_trips: 2, on_time_trips: 9, delayed_trips: 6, ghost_rate_pct: 42.31, on_time_pct: 60.0, avg_delay_sec: 325.0, max_delay_sec: 760 },
    { route_id: "110", route_name: "Route 110 Peachtree St", total_trips: 24, tracked_vehicles: 15, ghost_trips: 9, canceled_trips: 1, on_time_trips: 10, delayed_trips: 5, ghost_rate_pct: 37.5, on_time_pct: 66.67, avg_delay_sec: 280.0, max_delay_sec: 690 },
    { route_id: "73", route_name: "Route 73 Fulton Industrial", total_trips: 22, tracked_vehicles: 14, ghost_trips: 8, canceled_trips: 1, on_time_trips: 8, delayed_trips: 6, ghost_rate_pct: 36.36, on_time_pct: 57.14, avg_delay_sec: 350.0, max_delay_sec: 790 },
    { route_id: "RED-RAIL", route_name: "MARTA Red Line", total_trips: 28, tracked_vehicles: 24, ghost_trips: 4, canceled_trips: 0, on_time_trips: 20, delayed_trips: 4, ghost_rate_pct: 14.29, on_time_pct: 83.33, avg_delay_sec: 105.0, max_delay_sec: 260 },
  ],
  sample_ghost_trips: [
    { trip_id: "MARTA-8302", route_id: "83", start_time: "08:16", status: "SCHEDULED", reason: "Bus dropped transponder on Campbellton Rd arterial corridor" },
  ],
  coverage_details: {
    agency: "Metropolitan Atlanta Rapid Transit Authority (MARTA)",
    agency_desc: "Principal public transit operator in the Atlanta metropolitan area.",
    jurisdiction: "Atlanta, GA",
    jurisdiction_desc: "City of Atlanta, Fulton, DeKalb, and Clayton counties.",
    modes: "Heavy Rail & Bus Transit",
    modes_desc: "4 rail lines (Red, Gold, Blue, Green), Atlanta Streetcar, and over 100 bus routes.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Realtime web service protobuf feeds provided by itsmarta.com.",
    preset_info: "Open GTFS-RT Feed",
    preset_info_desc: "No API key required. CLI supported via `ghost-bus scan --preset atlanta`.",
  },
};

export const ATLANTA_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 22.1, overall_on_time_pct: 64.0, total_scheduled_trips: 520, total_tracked_vehicles: 405, total_ghost_trips: 115, mean_delay_sec: 198.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 20.59, overall_on_time_pct: 66.2, total_scheduled_trips: 510, total_tracked_vehicles: 405, total_ghost_trips: 105, mean_delay_sec: 185.0 },
];

export const TORONTO_LATEST = {
  scan_time: "2026-09-19T13:20:00.000000+00:00",
  feed_timestamp: 1789785600,
  agency: "TTC (Toronto)",
  city: "Toronto, ON",
  transit_system: "TTC",
  region: "Greater Toronto Area, Ontario",
  state: "Ontario",
  country: "Canada",
  total_scheduled_trips: 840,
  total_tracked_vehicles: 702,
  total_ghost_trips: 138,
  ghost_bus_rate_pct: 16.43,
  vehicle_tracking_rate_pct: 83.57,
  overall_on_time_pct: 71.2,
  delay_distribution: { early: 32, on_time: 495, minor_delay: 135, severe_delay: 40, ghost: 138, canceled: 12 },
  mean_delay_sec: 172.0,
  median_delay_sec: 75.0,
  worst_routes_by_ghost: [
    { route_id: "501", route_name: "501 Queen Streetcar", total_trips: 34, tracked_vehicles: 20, ghost_trips: 14, canceled_trips: 2, on_time_trips: 12, delayed_trips: 8, ghost_rate_pct: 41.18, on_time_pct: 60.0, avg_delay_sec: 345.0, max_delay_sec: 810 },
    { route_id: "504", route_name: "504 King Streetcar", total_trips: 32, tracked_vehicles: 21, ghost_trips: 11, canceled_trips: 1, on_time_trips: 14, delayed_trips: 7, ghost_rate_pct: 34.38, on_time_pct: 66.67, avg_delay_sec: 290.0, max_delay_sec: 680 },
    { route_id: "35", route_name: "35 Jane", total_trips: 28, tracked_vehicles: 19, ghost_trips: 9, canceled_trips: 1, on_time_trips: 12, delayed_trips: 7, ghost_rate_pct: 32.14, on_time_pct: 63.16, avg_delay_sec: 310.0, max_delay_sec: 720 },
    { route_id: "29", route_name: "29 Dufferin", total_trips: 30, tracked_vehicles: 21, ghost_trips: 9, canceled_trips: 1, on_time_trips: 14, delayed_trips: 7, ghost_rate_pct: 30.0, on_time_pct: 66.67, avg_delay_sec: 280.0, max_delay_sec: 670 },
    { route_id: "LINE-1", route_name: "Line 1 Yonge-University", total_trips: 36, tracked_vehicles: 32, ghost_trips: 4, canceled_trips: 0, on_time_trips: 28, delayed_trips: 4, ghost_rate_pct: 11.11, on_time_pct: 87.5, avg_delay_sec: 90.0, max_delay_sec: 240 },
  ],
  sample_ghost_trips: [
    { trip_id: "TTC-50192", route_id: "501", start_time: "08:12", status: "SCHEDULED", reason: "Streetcar short-turned at Sunnyside Loop without rider notification" },
    { trip_id: "TTC-35018", route_id: "35", start_time: "08:18", status: "SCHEDULED", reason: "Missing bus run north of Eglinton Ave on Jane St" },
  ],
  coverage_details: {
    agency: "Toronto Transit Commission (TTC)",
    agency_desc: "Third most heavily used urban mass transit system in North America after NYC and Mexico City.",
    jurisdiction: "Toronto, ON",
    jurisdiction_desc: "City of Toronto and Greater Toronto Area, Ontario, Canada.",
    modes: "Subway (Lines 1-4), Streetcar Network & Buses",
    modes_desc: "Extensive legacy streetcar network (11 routes), subway rapid transit, and over 140 bus lines.",
    protocol: "GTFS Realtime (GTFS-RT)",
    protocol_desc: "Open GTFS-RT protobuf feeds published by City of Toronto Open Data.",
    preset_info: "Open GTFS-RT Feed",
    preset_info_desc: "No API key required. CLI supported via `ghost-bus scan --preset toronto`.",
  },
};

export const TORONTO_HISTORY = [
  { scan_time: "2026-09-18 15:00:00", ghost_bus_rate_pct: 17.8, overall_on_time_pct: 69.5, total_scheduled_trips: 860, total_tracked_vehicles: 706, total_ghost_trips: 154, mean_delay_sec: 185.0 },
  { scan_time: "2026-09-19 13:20:00", ghost_bus_rate_pct: 16.43, overall_on_time_pct: 71.2, total_scheduled_trips: 840, total_tracked_vehicles: 702, total_ghost_trips: 138, mean_delay_sec: 172.0 },
];

export function normalizeCityKey(key) {
  if (!key) return "twin-cities";
  const clean = String(key).toLowerCase().trim().replace(/\s+/g, "-").replace(/_/g, "-");
  return CITY_ALIASES[clean] || "twin-cities";
}

export function getAllCitiesData(liveTwinCitiesLatest = null, liveTwinCitiesHistory = null) {
  const tcLatest = liveTwinCitiesLatest || DEFAULT_LATEST;
  const tcHistory = liveTwinCitiesHistory || DEFAULT_HISTORY;

  const twinCitiesSnapshot = {
    ...tcLatest,
    coverage_details: tcLatest.coverage_details || {
      agency: "Metro Transit",
      agency_desc: "Operating division of the Metropolitan Council; primary transit provider in the Twin Cities region.",
      jurisdiction: "Minneapolis & Saint Paul, MN",
      jurisdiction_desc: "State of Minnesota, USA. Covers Hennepin, Ramsey, Anoka, Carver, Dakota, Scott & Washington counties.",
      modes: "Bus, METRO Light Rail & BRT",
      modes_desc: "METRO Blue & Green Light Rail lines, METRO BRT (A, C, D, Orange, Red lines), and 100+ bus routes.",
      protocol: "GTFS Realtime (GTFS-RT)",
      protocol_desc: "Protocol Buffer feeds (vehiclepositions.pb & tripupdates.pb) via Metro Transit open data.",
      preset_info: "Default Open Feed",
      preset_info_desc: "Open public feed with zero authentication required. Automated git-scraping scans run every 30 minutes.",
    },
  };

  return {
    "twin-cities": {
      id: "twin-cities",
      name: "Twin Cities (Metro Transit)",
      shortName: "Twin Cities",
      agency: "Metro Transit",
      city: "Minneapolis–Saint Paul, MN",
      icon: "🏙️",
      website: "https://www.metrotransit.org",
      latest: twinCitiesSnapshot,
      history: Array.isArray(tcHistory) ? tcHistory : [tcHistory],
    },
    sf: {
      id: "sf",
      name: "San Francisco (SFMTA Muni)",
      shortName: "San Francisco",
      agency: "SFMTA (Muni)",
      city: "San Francisco, CA",
      icon: "🌉",
      website: "https://www.sfmta.com",
      latest: SF_LATEST,
      history: SF_HISTORY,
    },
    chicago: {
      id: "chicago",
      name: "Chicago (CTA)",
      shortName: "Chicago",
      agency: "Chicago Transit Authority",
      city: "Chicago, IL",
      icon: "🌆",
      website: "https://www.transitchicago.com",
      latest: CHICAGO_LATEST,
      history: CHICAGO_HISTORY,
    },
    boston: {
      id: "boston",
      name: "Boston (MBTA)",
      shortName: "Boston",
      agency: "MBTA",
      city: "Boston, MA",
      icon: "🏛️",
      website: "https://www.mbta.com",
      latest: BOSTON_LATEST,
      history: BOSTON_HISTORY,
    },
    nyc: {
      id: "nyc",
      name: "New York (MTA)",
      shortName: "New York",
      agency: "MTA New York City Transit",
      city: "New York, NY",
      icon: "🗽",
      website: "https://new.mta.info",
      latest: NYC_LATEST,
      history: NYC_HISTORY,
    },
    philly: {
      id: "philly",
      name: "Philadelphia (SEPTA)",
      shortName: "Philadelphia",
      agency: "SEPTA",
      city: "Philadelphia, PA",
      icon: "🔔",
      website: "https://www.septa.org",
      latest: PHILLY_LATEST,
      history: PHILLY_HISTORY,
    },
    dc: {
      id: "dc",
      name: "Washington, D.C. (WMATA)",
      shortName: "Washington D.C.",
      agency: "WMATA (Metro)",
      city: "Washington, DC",
      icon: "🏛️",
      website: "https://www.wmata.com",
      latest: DC_LATEST,
      history: DC_HISTORY,
    },
    la: {
      id: "la",
      name: "Los Angeles (LA Metro)",
      shortName: "Los Angeles",
      agency: "LA Metro",
      city: "Los Angeles, CA",
      icon: "🌴",
      website: "https://www.metro.net",
      latest: LA_LATEST,
      history: LA_HISTORY,
    },
    seattle: {
      id: "seattle",
      name: "Seattle (Sound Transit & KCM)",
      shortName: "Seattle",
      agency: "King County Metro / Sound Transit",
      city: "Seattle, WA",
      icon: "🌲",
      website: "https://kingcounty.gov/metro",
      latest: SEATTLE_LATEST,
      history: SEATTLE_HISTORY,
    },
    denver: {
      id: "denver",
      name: "Denver (RTD)",
      shortName: "Denver",
      agency: "RTD",
      city: "Denver, CO",
      icon: "🏔️",
      website: "https://www.rtd-denver.com",
      latest: DENVER_LATEST,
      history: DENVER_HISTORY,
    },
    portland: {
      id: "portland",
      name: "Portland (TriMet)",
      shortName: "Portland",
      agency: "TriMet",
      city: "Portland, OR",
      icon: "🌹",
      website: "https://trimet.org",
      latest: PORTLAND_LATEST,
      history: PORTLAND_HISTORY,
    },
    atlanta: {
      id: "atlanta",
      name: "Atlanta (MARTA)",
      shortName: "Atlanta",
      agency: "MARTA",
      city: "Atlanta, GA",
      icon: "🍑",
      website: "https://www.itsmarta.com",
      latest: ATLANTA_LATEST,
      history: ATLANTA_HISTORY,
    },
    toronto: {
      id: "toronto",
      name: "Toronto (TTC)",
      shortName: "Toronto",
      agency: "TTC",
      city: "Toronto, ON",
      icon: "🍁",
      website: "https://www.ttc.ca",
      latest: TORONTO_LATEST,
      history: TORONTO_HISTORY,
    },
  };
}
