export const DEFAULT_LATEST = {
  "scan_time": "2026-09-15T02:26:54.133109+00:00",
  "feed_timestamp": 1789439204,
  "agency": "Metro Transit (Twin Cities)",
  "total_scheduled_trips": 458,
  "total_tracked_vehicles": 380,
  "total_ghost_trips": 78,
  "ghost_bus_rate_pct": 17.03,
  "vehicle_tracking_rate_pct": 82.97,
  "overall_on_time_pct": 91.32,
  "delay_distribution": {
    "early": 11,
    "on_time": 347,
    "minor_delay": 20,
    "severe_delay": 2,
    "ghost": 78,
    "canceled": 10
  },
  "mean_delay_sec": 62.9,
  "median_delay_sec": 0.0,
  "worst_routes_by_ghost": [
    {
      "route_id": "71",
      "route_name": "Route 71",
      "total_trips": 8,
      "tracked_vehicles": 1,
      "ghost_trips": 7,
      "canceled_trips": 7,
      "on_time_trips": 0,
      "delayed_trips": 0,
      "ghost_rate_pct": 87.5,
      "on_time_pct": 0.0,
      "avg_delay_sec": -101.0,
      "max_delay_sec": -101
    },
    {
      "route_id": "725",
      "route_name": "Route 725",
      "total_trips": 4,
      "tracked_vehicles": 1,
      "ghost_trips": 3,
      "canceled_trips": 3,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 75.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": -3.0,
      "max_delay_sec": -3
    },
    {
      "route_id": "10",
      "route_name": "Route 10",
      "total_trips": 15,
      "tracked_vehicles": 7,
      "ghost_trips": 8,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 0,
      "ghost_rate_pct": 53.33,
      "on_time_pct": 100.0,
      "avg_delay_sec": 81.0,
      "max_delay_sec": 241
    },
    {
      "route_id": "18",
      "route_name": "Route 18",
      "total_trips": 25,
      "tracked_vehicles": 13,
      "ghost_trips": 12,
      "canceled_trips": 0,
      "on_time_trips": 12,
      "delayed_trips": 1,
      "ghost_rate_pct": 48.0,
      "on_time_pct": 92.31,
      "avg_delay_sec": 50.2,
      "max_delay_sec": 339
    },
    {
      "route_id": "17",
      "route_name": "Route 17",
      "total_trips": 12,
      "tracked_vehicles": 7,
      "ghost_trips": 5,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 0,
      "ghost_rate_pct": 41.67,
      "on_time_pct": 100.0,
      "avg_delay_sec": 96.4,
      "max_delay_sec": 275
    },
    {
      "route_id": "11",
      "route_name": "Route 11",
      "total_trips": 11,
      "tracked_vehicles": 7,
      "ghost_trips": 4,
      "canceled_trips": 0,
      "on_time_trips": 5,
      "delayed_trips": 2,
      "ghost_rate_pct": 36.36,
      "on_time_pct": 71.43,
      "avg_delay_sec": 126.6,
      "max_delay_sec": 434
    },
    {
      "route_id": "64",
      "route_name": "Route 64",
      "total_trips": 12,
      "tracked_vehicles": 8,
      "ghost_trips": 4,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 1,
      "ghost_rate_pct": 33.33,
      "on_time_pct": 85.71,
      "avg_delay_sec": 68.2,
      "max_delay_sec": 340
    },
    {
      "route_id": "14",
      "route_name": "Route 14",
      "total_trips": 9,
      "tracked_vehicles": 6,
      "ghost_trips": 3,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 33.33,
      "on_time_pct": 100.0,
      "avg_delay_sec": 38.2,
      "max_delay_sec": 146
    },
    {
      "route_id": "30",
      "route_name": "Route 30",
      "total_trips": 3,
      "tracked_vehicles": 2,
      "ghost_trips": 1,
      "canceled_trips": 0,
      "on_time_trips": 2,
      "delayed_trips": 0,
      "ghost_rate_pct": 33.33,
      "on_time_pct": 100.0,
      "avg_delay_sec": 9.5,
      "max_delay_sec": 19
    },
    {
      "route_id": "723",
      "route_name": "Route 723",
      "total_trips": 3,
      "tracked_vehicles": 2,
      "ghost_trips": 1,
      "canceled_trips": 0,
      "on_time_trips": 2,
      "delayed_trips": 0,
      "ghost_rate_pct": 33.33,
      "on_time_pct": 100.0,
      "avg_delay_sec": 0.0,
      "max_delay_sec": 0
    }
  ],
  "most_delayed_routes": [
    {
      "route_id": "645",
      "route_name": "Route 645",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 263.0,
      "max_delay_sec": 263
    },
    {
      "route_id": "4",
      "route_name": "Route 4",
      "total_trips": 8,
      "tracked_vehicles": 8,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 1,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 87.5,
      "avg_delay_sec": 189.6,
      "max_delay_sec": 984
    },
    {
      "route_id": "22",
      "route_name": "Route 22",
      "total_trips": 11,
      "tracked_vehicles": 9,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 2,
      "ghost_rate_pct": 18.18,
      "on_time_pct": 77.78,
      "avg_delay_sec": 179.6,
      "max_delay_sec": 968
    },
    {
      "route_id": "72",
      "route_name": "Route 72",
      "total_trips": 5,
      "tracked_vehicles": 5,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 3,
      "delayed_trips": 2,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 60.0,
      "avg_delay_sec": 154.8,
      "max_delay_sec": 442
    },
    {
      "route_id": "68",
      "route_name": "Route 68",
      "total_trips": 11,
      "tracked_vehicles": 8,
      "ghost_trips": 3,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 1,
      "ghost_rate_pct": 27.27,
      "on_time_pct": 87.5,
      "avg_delay_sec": 150.1,
      "max_delay_sec": 866
    },
    {
      "route_id": "827",
      "route_name": "Route 827",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 139.0,
      "max_delay_sec": 139
    },
    {
      "route_id": "9",
      "route_name": "Route 9",
      "total_trips": 8,
      "tracked_vehicles": 6,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 4,
      "delayed_trips": 2,
      "ghost_rate_pct": 25.0,
      "on_time_pct": 66.67,
      "avg_delay_sec": 130.2,
      "max_delay_sec": 449
    },
    {
      "route_id": "11",
      "route_name": "Route 11",
      "total_trips": 11,
      "tracked_vehicles": 7,
      "ghost_trips": 4,
      "canceled_trips": 0,
      "on_time_trips": 5,
      "delayed_trips": 2,
      "ghost_rate_pct": 36.36,
      "on_time_pct": 71.43,
      "avg_delay_sec": 126.6,
      "max_delay_sec": 434
    },
    {
      "route_id": "54",
      "route_name": "Route 54",
      "total_trips": 16,
      "tracked_vehicles": 15,
      "ghost_trips": 1,
      "canceled_trips": 0,
      "on_time_trips": 13,
      "delayed_trips": 2,
      "ghost_rate_pct": 6.25,
      "on_time_pct": 86.67,
      "avg_delay_sec": 121.1,
      "max_delay_sec": 710
    },
    {
      "route_id": "61",
      "route_name": "Route 61",
      "total_trips": 9,
      "tracked_vehicles": 8,
      "ghost_trips": 1,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 1,
      "ghost_rate_pct": 11.11,
      "on_time_pct": 87.5,
      "avg_delay_sec": 112.6,
      "max_delay_sec": 329
    }
  ],
  "route_metrics": [
    {
      "route_id": "10",
      "route_name": "Route 10",
      "total_trips": 15,
      "tracked_vehicles": 7,
      "ghost_trips": 8,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 0,
      "ghost_rate_pct": 53.33,
      "on_time_pct": 100.0,
      "avg_delay_sec": 81.0,
      "max_delay_sec": 241
    },
    {
      "route_id": "11",
      "route_name": "Route 11",
      "total_trips": 11,
      "tracked_vehicles": 7,
      "ghost_trips": 4,
      "canceled_trips": 0,
      "on_time_trips": 5,
      "delayed_trips": 2,
      "ghost_rate_pct": 36.36,
      "on_time_pct": 71.43,
      "avg_delay_sec": 126.6,
      "max_delay_sec": 434
    },
    {
      "route_id": "14",
      "route_name": "Route 14",
      "total_trips": 9,
      "tracked_vehicles": 6,
      "ghost_trips": 3,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 33.33,
      "on_time_pct": 100.0,
      "avg_delay_sec": 38.2,
      "max_delay_sec": 146
    },
    {
      "route_id": "17",
      "route_name": "Route 17",
      "total_trips": 12,
      "tracked_vehicles": 7,
      "ghost_trips": 5,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 0,
      "ghost_rate_pct": 41.67,
      "on_time_pct": 100.0,
      "avg_delay_sec": 96.4,
      "max_delay_sec": 275
    },
    {
      "route_id": "18",
      "route_name": "Route 18",
      "total_trips": 25,
      "tracked_vehicles": 13,
      "ghost_trips": 12,
      "canceled_trips": 0,
      "on_time_trips": 12,
      "delayed_trips": 1,
      "ghost_rate_pct": 48.0,
      "on_time_pct": 92.31,
      "avg_delay_sec": 50.2,
      "max_delay_sec": 339
    },
    {
      "route_id": "2",
      "route_name": "Route 2",
      "total_trips": 8,
      "tracked_vehicles": 8,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 8,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 37.2,
      "max_delay_sec": 154
    },
    {
      "route_id": "215",
      "route_name": "Route 215",
      "total_trips": 3,
      "tracked_vehicles": 3,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 3,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 18.7,
      "max_delay_sec": 56
    },
    {
      "route_id": "219",
      "route_name": "Route 219",
      "total_trips": 2,
      "tracked_vehicles": 2,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 91.5,
      "max_delay_sec": 257
    },
    {
      "route_id": "22",
      "route_name": "Route 22",
      "total_trips": 11,
      "tracked_vehicles": 9,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 2,
      "ghost_rate_pct": 18.18,
      "on_time_pct": 77.78,
      "avg_delay_sec": 179.6,
      "max_delay_sec": 968
    },
    {
      "route_id": "27",
      "route_name": "Route 27",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 0.0,
      "max_delay_sec": 0
    },
    {
      "route_id": "3",
      "route_name": "Route 3",
      "total_trips": 13,
      "tracked_vehicles": 11,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 11,
      "delayed_trips": 0,
      "ghost_rate_pct": 15.38,
      "on_time_pct": 100.0,
      "avg_delay_sec": 82.2,
      "max_delay_sec": 263
    },
    {
      "route_id": "30",
      "route_name": "Route 30",
      "total_trips": 3,
      "tracked_vehicles": 2,
      "ghost_trips": 1,
      "canceled_trips": 0,
      "on_time_trips": 2,
      "delayed_trips": 0,
      "ghost_rate_pct": 33.33,
      "on_time_pct": 100.0,
      "avg_delay_sec": 9.5,
      "max_delay_sec": 19
    },
    {
      "route_id": "32",
      "route_name": "Route 32",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 0.0,
      "max_delay_sec": 0
    },
    {
      "route_id": "323",
      "route_name": "Route 323",
      "total_trips": 3,
      "tracked_vehicles": 3,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 3,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 35.7,
      "max_delay_sec": 107
    },
    {
      "route_id": "36",
      "route_name": "Route 36",
      "total_trips": 8,
      "tracked_vehicles": 6,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 25.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 57.0,
      "max_delay_sec": 228
    },
    {
      "route_id": "38",
      "route_name": "Route 38",
      "total_trips": 9,
      "tracked_vehicles": 9,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 8,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 4.1,
      "max_delay_sec": 180
    },
    {
      "route_id": "4",
      "route_name": "Route 4",
      "total_trips": 8,
      "tracked_vehicles": 8,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 1,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 87.5,
      "avg_delay_sec": 189.6,
      "max_delay_sec": 984
    },
    {
      "route_id": "46",
      "route_name": "Route 46",
      "total_trips": 2,
      "tracked_vehicles": 2,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 2,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 0.0,
      "max_delay_sec": 0
    },
    {
      "route_id": "48",
      "route_name": "Route 48",
      "total_trips": 4,
      "tracked_vehicles": 4,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 4,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": -1.0,
      "max_delay_sec": 15
    },
    {
      "route_id": "5",
      "route_name": "Route 5",
      "total_trips": 3,
      "tracked_vehicles": 3,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 3,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": -4.0,
      "max_delay_sec": 0
    },
    {
      "route_id": "515",
      "route_name": "Route 515",
      "total_trips": 6,
      "tracked_vehicles": 6,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 31.0,
      "max_delay_sec": 94
    },
    {
      "route_id": "534",
      "route_name": "Route 534",
      "total_trips": 6,
      "tracked_vehicles": 6,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 5,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": -8.5,
      "max_delay_sec": 29
    },
    {
      "route_id": "538",
      "route_name": "Route 538",
      "total_trips": 2,
      "tracked_vehicles": 2,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 2,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 34.5,
      "max_delay_sec": 99
    },
    {
      "route_id": "539",
      "route_name": "Route 539",
      "total_trips": 6,
      "tracked_vehicles": 6,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 28.5,
      "max_delay_sec": 91
    },
    {
      "route_id": "54",
      "route_name": "Route 54",
      "total_trips": 16,
      "tracked_vehicles": 15,
      "ghost_trips": 1,
      "canceled_trips": 0,
      "on_time_trips": 13,
      "delayed_trips": 2,
      "ghost_rate_pct": 6.25,
      "on_time_pct": 86.67,
      "avg_delay_sec": 121.1,
      "max_delay_sec": 710
    },
    {
      "route_id": "540",
      "route_name": "Route 540",
      "total_trips": 8,
      "tracked_vehicles": 6,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 25.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 63.7,
      "max_delay_sec": 193
    },
    {
      "route_id": "546",
      "route_name": "Route 546",
      "total_trips": 6,
      "tracked_vehicles": 6,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 44.2,
      "max_delay_sec": 262
    },
    {
      "route_id": "61",
      "route_name": "Route 61",
      "total_trips": 9,
      "tracked_vehicles": 8,
      "ghost_trips": 1,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 1,
      "ghost_rate_pct": 11.11,
      "on_time_pct": 87.5,
      "avg_delay_sec": 112.6,
      "max_delay_sec": 329
    },
    {
      "route_id": "62",
      "route_name": "Route 62",
      "total_trips": 9,
      "tracked_vehicles": 7,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 0,
      "ghost_rate_pct": 22.22,
      "on_time_pct": 100.0,
      "avg_delay_sec": 64.1,
      "max_delay_sec": 221
    },
    {
      "route_id": "63",
      "route_name": "Route 63",
      "total_trips": 10,
      "tracked_vehicles": 8,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 1,
      "ghost_rate_pct": 20.0,
      "on_time_pct": 85.71,
      "avg_delay_sec": 43.2,
      "max_delay_sec": 341
    },
    {
      "route_id": "64",
      "route_name": "Route 64",
      "total_trips": 12,
      "tracked_vehicles": 8,
      "ghost_trips": 4,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 1,
      "ghost_rate_pct": 33.33,
      "on_time_pct": 85.71,
      "avg_delay_sec": 68.2,
      "max_delay_sec": 340
    },
    {
      "route_id": "645",
      "route_name": "Route 645",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 263.0,
      "max_delay_sec": 263
    },
    {
      "route_id": "65",
      "route_name": "Route 65",
      "total_trips": 2,
      "tracked_vehicles": 2,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 2,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 0.0,
      "max_delay_sec": 0
    },
    {
      "route_id": "67",
      "route_name": "Route 67",
      "total_trips": 3,
      "tracked_vehicles": 3,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 3,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 61.0,
      "max_delay_sec": 207
    },
    {
      "route_id": "68",
      "route_name": "Route 68",
      "total_trips": 11,
      "tracked_vehicles": 8,
      "ghost_trips": 3,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 1,
      "ghost_rate_pct": 27.27,
      "on_time_pct": 87.5,
      "avg_delay_sec": 150.1,
      "max_delay_sec": 866
    },
    {
      "route_id": "686",
      "route_name": "Route 686",
      "total_trips": 5,
      "tracked_vehicles": 5,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 5,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": -9.6,
      "max_delay_sec": 10
    },
    {
      "route_id": "7",
      "route_name": "Route 7",
      "total_trips": 8,
      "tracked_vehicles": 6,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 25.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 51.2,
      "max_delay_sec": 140
    },
    {
      "route_id": "705",
      "route_name": "Route 705",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": -44.0,
      "max_delay_sec": -44
    },
    {
      "route_id": "71",
      "route_name": "Route 71",
      "total_trips": 8,
      "tracked_vehicles": 1,
      "ghost_trips": 7,
      "canceled_trips": 7,
      "on_time_trips": 0,
      "delayed_trips": 0,
      "ghost_rate_pct": 87.5,
      "on_time_pct": 0.0,
      "avg_delay_sec": -101.0,
      "max_delay_sec": -101
    },
    {
      "route_id": "717",
      "route_name": "Route 717",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 0.0,
      "max_delay_sec": 0
    },
    {
      "route_id": "72",
      "route_name": "Route 72",
      "total_trips": 5,
      "tracked_vehicles": 5,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 3,
      "delayed_trips": 2,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 60.0,
      "avg_delay_sec": 154.8,
      "max_delay_sec": 442
    },
    {
      "route_id": "721",
      "route_name": "Route 721",
      "total_trips": 3,
      "tracked_vehicles": 3,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 3,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 54.0,
      "max_delay_sec": 162
    },
    {
      "route_id": "722",
      "route_name": "Route 722",
      "total_trips": 5,
      "tracked_vehicles": 5,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 5,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 1.8,
      "max_delay_sec": 13
    },
    {
      "route_id": "723",
      "route_name": "Route 723",
      "total_trips": 3,
      "tracked_vehicles": 2,
      "ghost_trips": 1,
      "canceled_trips": 0,
      "on_time_trips": 2,
      "delayed_trips": 0,
      "ghost_rate_pct": 33.33,
      "on_time_pct": 100.0,
      "avg_delay_sec": 0.0,
      "max_delay_sec": 0
    },
    {
      "route_id": "724",
      "route_name": "Route 724",
      "total_trips": 6,
      "tracked_vehicles": 6,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 4,
      "delayed_trips": 1,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 80.0,
      "avg_delay_sec": 97.7,
      "max_delay_sec": 516
    },
    {
      "route_id": "725",
      "route_name": "Route 725",
      "total_trips": 4,
      "tracked_vehicles": 1,
      "ghost_trips": 3,
      "canceled_trips": 3,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 75.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": -3.0,
      "max_delay_sec": -3
    },
    {
      "route_id": "74",
      "route_name": "Route 74",
      "total_trips": 8,
      "tracked_vehicles": 8,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": -7.5,
      "max_delay_sec": 55
    },
    {
      "route_id": "80",
      "route_name": "Route 80",
      "total_trips": 3,
      "tracked_vehicles": 3,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 2,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 23.7,
      "max_delay_sec": 146
    },
    {
      "route_id": "802",
      "route_name": "Route 802",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 51.0,
      "max_delay_sec": 51
    },
    {
      "route_id": "827",
      "route_name": "Route 827",
      "total_trips": 1,
      "tracked_vehicles": 1,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 1,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 139.0,
      "max_delay_sec": 139
    },
    {
      "route_id": "87",
      "route_name": "Route 87",
      "total_trips": 4,
      "tracked_vehicles": 4,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 3,
      "delayed_trips": 1,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 75.0,
      "avg_delay_sec": 99.2,
      "max_delay_sec": 375
    },
    {
      "route_id": "9",
      "route_name": "Route 9",
      "total_trips": 8,
      "tracked_vehicles": 6,
      "ghost_trips": 2,
      "canceled_trips": 0,
      "on_time_trips": 4,
      "delayed_trips": 2,
      "ghost_rate_pct": 25.0,
      "on_time_pct": 66.67,
      "avg_delay_sec": 130.2,
      "max_delay_sec": 449
    },
    {
      "route_id": "901",
      "route_name": "Route 901",
      "total_trips": 5,
      "tracked_vehicles": 5,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 5,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 60.0,
      "max_delay_sec": 180
    },
    {
      "route_id": "902",
      "route_name": "Route 902",
      "total_trips": 8,
      "tracked_vehicles": 8,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 8,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 52.5,
      "max_delay_sec": 240
    },
    {
      "route_id": "903",
      "route_name": "Route 903",
      "total_trips": 6,
      "tracked_vehicles": 6,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 6,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 10.2,
      "max_delay_sec": 37
    },
    {
      "route_id": "904",
      "route_name": "Route 904",
      "total_trips": 13,
      "tracked_vehicles": 13,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 12,
      "delayed_trips": 1,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 92.31,
      "avg_delay_sec": 95.8,
      "max_delay_sec": 369
    },
    {
      "route_id": "905",
      "route_name": "Route 905",
      "total_trips": 7,
      "tracked_vehicles": 7,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 25.0,
      "max_delay_sec": 215
    },
    {
      "route_id": "921",
      "route_name": "Route 921",
      "total_trips": 20,
      "tracked_vehicles": 14,
      "ghost_trips": 6,
      "canceled_trips": 0,
      "on_time_trips": 13,
      "delayed_trips": 1,
      "ghost_rate_pct": 30.0,
      "on_time_pct": 92.86,
      "avg_delay_sec": 57.6,
      "max_delay_sec": 380
    },
    {
      "route_id": "922",
      "route_name": "Route 922",
      "total_trips": 15,
      "tracked_vehicles": 15,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 14,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 40.1,
      "max_delay_sec": 214
    },
    {
      "route_id": "923",
      "route_name": "Route 923",
      "total_trips": 11,
      "tracked_vehicles": 11,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 9,
      "delayed_trips": 1,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 90.0,
      "avg_delay_sec": 37.9,
      "max_delay_sec": 303
    },
    {
      "route_id": "924",
      "route_name": "Route 924",
      "total_trips": 20,
      "tracked_vehicles": 17,
      "ghost_trips": 3,
      "canceled_trips": 0,
      "on_time_trips": 17,
      "delayed_trips": 0,
      "ghost_rate_pct": 15.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 51.9,
      "max_delay_sec": 210
    },
    {
      "route_id": "925",
      "route_name": "Route 925",
      "total_trips": 14,
      "tracked_vehicles": 14,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 13,
      "delayed_trips": 1,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 92.86,
      "avg_delay_sec": 61.1,
      "max_delay_sec": 313
    },
    {
      "route_id": "94",
      "route_name": "Route 94",
      "total_trips": 7,
      "tracked_vehicles": 7,
      "ghost_trips": 0,
      "canceled_trips": 0,
      "on_time_trips": 7,
      "delayed_trips": 0,
      "ghost_rate_pct": 0.0,
      "on_time_pct": 100.0,
      "avg_delay_sec": 42.7,
      "max_delay_sec": 151
    }
  ],
  "sample_ghost_trips": [
    {
      "trip_id": "1325266",
      "route_id": "10",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1325324",
      "route_id": "10",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1325371",
      "route_id": "10",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1325738",
      "route_id": "10",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1325888",
      "route_id": "10",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1326807",
      "route_id": "10",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1327003",
      "route_id": "10",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1327013",
      "route_id": "10",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1319546",
      "route_id": "11",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1319569",
      "route_id": "11",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1349623",
      "route_id": "11",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1351646",
      "route_id": "11",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1332593",
      "route_id": "14",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1332889",
      "route_id": "14",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    },
    {
      "trip_id": "1333220",
      "route_id": "14",
      "start_time": "N/A",
      "start_date": "20260914",
      "status": "SCHEDULED",
      "reason": "No vehicle assigned and no active GPS broadcast"
    }
  ],
  "headway_metrics": [
    {
      "route_id": "4",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 18.2,
      "excess_wait_time_min": 2.67,
      "headway_regularity_score": 46.6
    },
    {
      "route_id": "22",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 18.0,
      "excess_wait_time_min": 2.48,
      "headway_regularity_score": 50.3
    },
    {
      "route_id": "68",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 17.5,
      "excess_wait_time_min": 2.29,
      "headway_regularity_score": 54.1
    },
    {
      "route_id": "72",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 17.6,
      "excess_wait_time_min": 1.73,
      "headway_regularity_score": 65.4
    },
    {
      "route_id": "724",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 16.6,
      "excess_wait_time_min": 1.67,
      "headway_regularity_score": 66.6
    },
    {
      "route_id": "11",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 17.1,
      "excess_wait_time_min": 1.58,
      "headway_regularity_score": 68.4
    },
    {
      "route_id": "54",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 17.0,
      "excess_wait_time_min": 1.53,
      "headway_regularity_score": 69.4
    },
    {
      "route_id": "9",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 17.2,
      "excess_wait_time_min": 1.53,
      "headway_regularity_score": 69.3
    },
    {
      "route_id": "38",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 15.1,
      "excess_wait_time_min": 1.47,
      "headway_regularity_score": 70.7
    },
    {
      "route_id": "219",
      "scheduled_headway_min": 15.0,
      "observed_headway_min": 16.5,
      "excess_wait_time_min": 1.38,
      "headway_regularity_score": 72.4
    }
  ]
};

export const DEFAULT_HISTORY = [
  {
    "scan_time": "2026-09-14T00:35:12.771265+00:00",
    "ghost_bus_rate_pct": 13.63,
    "overall_on_time_pct": 73.3,
    "total_scheduled_trips": 477,
    "total_tracked_vehicles": 412,
    "total_ghost_trips": 65,
    "mean_delay_sec": 242.2
  },
  {
    "scan_time": "2026-09-14T00:35:23.071428+00:00",
    "ghost_bus_rate_pct": 13.63,
    "overall_on_time_pct": 73.3,
    "total_scheduled_trips": 477,
    "total_tracked_vehicles": 412,
    "total_ghost_trips": 65,
    "mean_delay_sec": 242.2
  },
  {
    "scan_time": "2026-09-14T00:36:37.249091+00:00",
    "ghost_bus_rate_pct": 13.36,
    "overall_on_time_pct": 73.73,
    "total_scheduled_trips": 479,
    "total_tracked_vehicles": 415,
    "total_ghost_trips": 64,
    "mean_delay_sec": 257.4
  },
  {
    "scan_time": "2026-09-14T00:36:42.708679+00:00",
    "ghost_bus_rate_pct": 13.36,
    "overall_on_time_pct": 73.73,
    "total_scheduled_trips": 479,
    "total_tracked_vehicles": 415,
    "total_ghost_trips": 64,
    "mean_delay_sec": 257.4
  },
  {
    "scan_time": "2026-09-14T00:36:50.166021+00:00",
    "ghost_bus_rate_pct": 13.36,
    "overall_on_time_pct": 73.73,
    "total_scheduled_trips": 479,
    "total_tracked_vehicles": 414,
    "total_ghost_trips": 64,
    "mean_delay_sec": 257.4
  },
  {
    "scan_time": "2026-09-14T00:41:28.827985+00:00",
    "ghost_bus_rate_pct": 14.01,
    "overall_on_time_pct": 72.03,
    "total_scheduled_trips": 471,
    "total_tracked_vehicles": 405,
    "total_ghost_trips": 66,
    "mean_delay_sec": 275.1
  },
  {
    "scan_time": "2026-09-14T00:41:35.799649+00:00",
    "ghost_bus_rate_pct": 14.01,
    "overall_on_time_pct": 72.03,
    "total_scheduled_trips": 471,
    "total_tracked_vehicles": 405,
    "total_ghost_trips": 66,
    "mean_delay_sec": 275.1
  },
  {
    "scan_time": "2026-09-14T00:42:36.543175+00:00",
    "ghost_bus_rate_pct": 13.63,
    "overall_on_time_pct": 73.3,
    "total_scheduled_trips": 477,
    "total_tracked_vehicles": 412,
    "total_ghost_trips": 65,
    "mean_delay_sec": 242.2
  },
  {
    "scan_time": "2026-09-14T01:09:20.106229+00:00",
    "ghost_bus_rate_pct": 14.1,
    "overall_on_time_pct": 66.41,
    "total_scheduled_trips": 454,
    "total_tracked_vehicles": 390,
    "total_ghost_trips": 64,
    "mean_delay_sec": 284.0
  },
  {
    "scan_time": "2026-09-14T05:33:56.193205+00:00",
    "ghost_bus_rate_pct": 2.25,
    "overall_on_time_pct": 80.46,
    "total_scheduled_trips": 89,
    "total_tracked_vehicles": 87,
    "total_ghost_trips": 2,
    "mean_delay_sec": 102.8
  },
  {
    "scan_time": "2026-09-14T11:14:14.332197+00:00",
    "ghost_bus_rate_pct": 20.62,
    "overall_on_time_pct": 92.93,
    "total_scheduled_trips": 873,
    "total_tracked_vehicles": 693,
    "total_ghost_trips": 180,
    "mean_delay_sec": 40.3
  },
  {
    "scan_time": "2026-09-14T16:59:54.904717+00:00",
    "ghost_bus_rate_pct": 19.2,
    "overall_on_time_pct": 86.8,
    "total_scheduled_trips": 901,
    "total_tracked_vehicles": 728,
    "total_ghost_trips": 173,
    "mean_delay_sec": 60.5
  },
  {
    "scan_time": "2026-09-14T20:46:08.479584+00:00",
    "ghost_bus_rate_pct": 17.07,
    "overall_on_time_pct": 80.61,
    "total_scheduled_trips": 1113,
    "total_tracked_vehicles": 923,
    "total_ghost_trips": 190,
    "mean_delay_sec": 111.2
  },
  {
    "scan_time": "2026-09-14T23:35:16.321773+00:00",
    "ghost_bus_rate_pct": 16.58,
    "overall_on_time_pct": 81.7,
    "total_scheduled_trips": 760,
    "total_tracked_vehicles": 634,
    "total_ghost_trips": 126,
    "mean_delay_sec": 110.4
  },
  {
    "scan_time": "2026-09-15T02:26:54.133109+00:00",
    "ghost_bus_rate_pct": 17.03,
    "overall_on_time_pct": 91.32,
    "total_scheduled_trips": 458,
    "total_tracked_vehicles": 380,
    "total_ghost_trips": 78,
    "mean_delay_sec": 62.9
  }
];
